/**
 * Resolution of the Python runtime bundled beside the packaged application.
 *
 * The Windows package ships the official embeddable CPython tree under
 * `resources/python-runtime`. Unlike the bundled Node runtime (one command
 * file), Python is a directory tree, so integrity is pinned per file: the
 * build-time manifest `lib/python-runtime-sha256.json` (generated by
 * `scripts/bundled-python.ts` right after staging — which also bootstraps
 * pip and a pinned virtualenv into the tree) maps every relative file to its
 * sha256, and the packaged runtime refuses the whole surface when the
 * physical tree deviates — a missing, extra, or tampered file all fail
 * closed. The bootstrap-grown tree is a few thousand files (≈40 MiB), which
 * still hashes in a fraction of a second, so every launch of the Python
 * surface re-verifies in full, and an unchanged `(mtime, size)` fingerprint
 * only short-circuits re-spawns within one process.
 */

import { createHash } from 'node:crypto'
import { readFileSync, readdirSync, statSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { archivedAsarPath, isPackagedApplicationPath } from './packaged-runtime-path.ts'

/** Directory extraResources places the pinned Python distribution into. */
const BUNDLED_PYTHON_DIRECTORY = 'python-runtime'

/**
 * Build-time digest manifest shipped at `lib/python-runtime-sha256.json`.
 *
 * `beforePack` generates it from the staged tree (see
 * `scripts/bundled-python.ts`), so the digests are deterministic per pinned
 * CPython version. The manifest is dual-homed like every `lib/**` asset, and
 * the runtime reads it through the in-archive path, which only the Electron
 * process can serve.
 */
export const BUNDLED_PYTHON_DIGEST_MANIFEST_NAME = 'python-runtime-sha256.json'

/** Parsed contents of `lib/python-runtime-sha256.json`. */
export interface BundledPythonDigestManifest {
  /** Pinned CPython version the digests were computed from. */
  readonly version: string
  /** Packaging platform (`win32`) the manifest covers. */
  readonly platform: string
  /** sha256 digest of every bundled file, keyed by forward-slash-relative path. */
  readonly files: Readonly<Record<string, string>>
}

/** Return the command name the bundled Python distribution installs as. */
export function bundledPythonCommandName(): string {
  return 'python.exe'
}

/** Inputs controlling one Python-runtime resolution. */
export interface DesktopPythonRuntimeInputs {
  /** Host platform; only the Windows embeddable distribution is bundled. */
  readonly platform: NodeJS.Platform
  /** Environment whose PATH is searched in the unpackaged development state. */
  readonly environment?: NodeJS.ProcessEnv
  /** Regular-file probe; production uses `statSync`. */
  readonly exists?: (filename: string) => boolean
  /** Digest-manifest reader; production reads the archive-side manifest. */
  readonly readDigestManifest?: (filename: string) => string
  /** Relative-file walker over the bundled tree; production walks with `readdirSync`. */
  readonly listRuntimeFiles?: (directory: string) => readonly string[]
  /** Stat seam backing the verified-tree cache; production uses `statSync`. */
  readonly statFile?: (filename: string) => { readonly mtimeMs: number, readonly size: number }
  /** sha256 seam over one bundled file; production hashes with node:crypto. */
  readonly digestFile?: (filename: string) => string
}

function isRegularFile(filename: string): boolean {
  try {
    return statSync(filename).isFile()
  } catch {
    return false
  }
}

/** Read PATH with Windows-compatible environment-name matching. */
function inheritedPathValue(environment: NodeJS.ProcessEnv, platform: NodeJS.Platform): string {
  if (platform !== 'win32') return environment.PATH ?? ''
  return Object.entries(environment)
    .find(([key]) => key.toUpperCase() === 'PATH')?.[1] ?? ''
}

/** List every file below one directory as sorted forward-slash-relative paths. */
function listRuntimeFilesImpl(directory: string): readonly string[] {
  const files: string[] = []
  const walk = (current: string): void => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const full = join(current, entry.name)
      if (entry.isDirectory()) walk(full)
      else if (entry.isFile()) files.push(relativePosix(directory, full))
    }
  }
  walk(directory)
  return files.sort((left, right) => left < right ? -1 : left > right ? 1 : 0)
}

/** Relative path from one directory to one file, normalized to forward slashes. */
function relativePosix(from: string, to: string): string {
  return relative(from, to).replaceAll('\\', '/')
}

/**
 * Resolve the bundled Python directory beside this module's packaged tree.
 *
 * A packaged module lives at `<resources>/app.asar.unpacked/lib/<name>.js`,
 * so the physical bundle is `<resources>/python-runtime/`; in an unpackaged
 * checkout the same computation points at a directory that does not exist
 * and callers fall back to the development PATH lookup below.
 * @param moduleUrl - URL of a module emitted below the package's `lib` directory.
 * @returns the bundled Python directory for this application layout.
 */
export function packagedBundledPythonDirectory(moduleUrl: string): string {
  const moduleDirectory = dirname(fileURLToPath(new URL(moduleUrl)))
  return join(dirname(dirname(moduleDirectory)), BUNDLED_PYTHON_DIRECTORY)
}

/**
 * Resolve the in-archive digest manifest beside a built module inside `lib/`.
 *
 * The manifest is read through the virtual `app.asar` path: only the
 * Electron process can serve it, and the archive-side copy is the one the
 * packaged-runtime gate pins. Outside a package the path simply points at
 * the development `lib/`.
 * @param moduleUrl - URL of a module emitted below the package's `lib` directory.
 * @returns the digest-manifest path for this application layout.
 */
export function bundledPythonDigestManifestPath(moduleUrl: string): string {
  return join(
    dirname(archivedAsarPath(fileURLToPath(new URL(moduleUrl)))),
    BUNDLED_PYTHON_DIGEST_MANIFEST_NAME,
  )
}

/** Whether one module URL belongs to a packaged application tree. */
export function isPackagedModuleUrl(moduleUrl: string): boolean {
  return isPackagedApplicationPath(fileURLToPath(new URL(moduleUrl)))
}

/** Strictly parse one digest manifest document; every deviation throws. */
export function parseBundledPythonDigestManifest(value: unknown): BundledPythonDigestManifest {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('dsh-plugin-desktop: bundled Python digest manifest must be an object')
  }
  const object = value as Record<string, unknown>
  const keys = Object.keys(object).sort()
  if (keys.length !== 3 || keys[0] !== 'files' || keys[1] !== 'platform' || keys[2] !== 'version') {
    throw new Error('dsh-plugin-desktop: bundled Python digest manifest has unexpected fields')
  }
  if (typeof object.version !== 'string' || object.version.length === 0) {
    throw new Error('dsh-plugin-desktop: bundled Python digest manifest version must be a non-empty string')
  }
  if (typeof object.platform !== 'string' || object.platform.length === 0) {
    throw new Error('dsh-plugin-desktop: bundled Python digest manifest platform must be a non-empty string')
  }
  const files = object.files
  if (files === null || typeof files !== 'object' || Array.isArray(files)) {
    throw new Error('dsh-plugin-desktop: bundled Python digest manifest files must be an object')
  }
  const entries = Object.entries(files as Record<string, unknown>)
  if (entries.length === 0) {
    throw new Error('dsh-plugin-desktop: bundled Python digest manifest files must not be empty')
  }
  const parsed: Record<string, string> = {}
  for (const [relativePath, digest] of entries) {
    const segments = relativePath.split('/')
    const unsafe = relativePath.length === 0
      || relativePath.includes('\\')
      || relativePath.startsWith('/')
      || /^[A-Za-z]:/.test(relativePath)
      || segments.includes('..')
      || segments.includes('.')
      || segments.includes('')
    if (unsafe || typeof digest !== 'string' || !/^[0-9a-f]{64}$/u.test(digest)) {
      throw new Error(
        `dsh-plugin-desktop: bundled Python digest manifest entry ${JSON.stringify(relativePath)} must be a safe relative path pinning a sha256 hex digest`,
      )
    }
    parsed[relativePath] = digest
  }
  return Object.freeze({ version: object.version, platform: object.platform, files: Object.freeze(parsed) })
}

/** File identity of one verified bundled Python file. */
interface VerifiedFileFingerprint {
  readonly mtimeMs: number
  readonly size: number
}

/**
 * Verified-tree cache: `(mtime, size)` per file keyed by the bundled
 * directory. The tree hashes in milliseconds, so — unlike the bundled Node
 * command — every first use of a process verifies in full; the cache only
 * keeps re-spawns and repeated resolutions within one process cheap.
 */
const verifiedBundledPythonRuntimes = new Map<string, ReadonlyMap<string, VerifiedFileFingerprint>>()

/** Reset the verified-tree cache; used by focused tests. */
export function clearBundledPythonRuntimeVerificationCache(): void {
  verifiedBundledPythonRuntimes.clear()
}

function readDigestManifestFile(filename: string): string {
  return readFileSync(filename, 'utf8')
}

function statFileIdentity(filename: string): { readonly mtimeMs: number, readonly size: number } {
  const stats = statSync(filename)
  return { mtimeMs: stats.mtimeMs, size: stats.size }
}

function digestFileBytes(filename: string): string {
  return createHash('sha256').update(readFileSync(filename)).digest('hex')
}

/**
 * Verify one bundled Python tree against the packaged digest manifest.
 *
 * Advisory positioning (mirroring the bundled Node command): the manifest
 * raises the cost of tampering with the user-writable
 * `resources/python-runtime` tree — a swapped or injected file must now be
 * accompanied by a consistent rewrite of the shipped manifest inside the
 * application tree — but it is not a boundary; a binding guarantee needs
 * platform code signing. The exact-set check (no missing and no extra file)
 * also blocks dropping executable importables such as `sitecustomize.py`
 * into the tree the unlocked `._pth` would load.
 * @param moduleUrl - module URL locating the archive-side manifest.
 * @param directory - bundled Python directory the caller resolved.
 * @param inputs - injectable manifest, walker, stat, and digest seams.
 */
function verifyBundledPythonRuntimeIntegrity(
  moduleUrl: string,
  directory: string,
  inputs: DesktopPythonRuntimeInputs,
): void {
  const manifestPath = bundledPythonDigestManifestPath(moduleUrl)
  let manifestText: string
  try {
    manifestText = (inputs.readDigestManifest ?? readDigestManifestFile)(manifestPath)
  } catch (cause) {
    throw new Error(
      `dsh-plugin-desktop: the packaged digest manifest is unreadable at ${manifestPath}: `
      + `${cause instanceof Error ? cause.message : String(cause)}; packaged Windows applications ship `
      + `${BUNDLED_PYTHON_DIGEST_MANIFEST_NAME} beside lib/, so reinstall DSH Desktop`,
    )
  }
  let manifest: BundledPythonDigestManifest
  try {
    manifest = parseBundledPythonDigestManifest(JSON.parse(manifestText) as unknown)
  } catch (cause) {
    throw new Error(
      `dsh-plugin-desktop: invalid bundled Python digest manifest at ${manifestPath}: `
      + `${cause instanceof Error ? cause.message : String(cause)}`,
    )
  }
  if (manifest.platform !== inputs.platform) {
    throw new Error(
      `dsh-plugin-desktop: bundled Python digest manifest at ${manifestPath} covers platform `
      + `${JSON.stringify(manifest.platform)} but this application runs on ${inputs.platform}`,
    )
  }
  const listRuntimeFiles = inputs.listRuntimeFiles ?? listRuntimeFilesImpl
  const statFile = inputs.statFile ?? statFileIdentity
  const digestFile = inputs.digestFile ?? digestFileBytes
  const listed = listRuntimeFiles(directory)
  const pinned = Object.keys(manifest.files).sort()
  const listedSorted = [...listed].sort()
  if (listedSorted.length !== pinned.length || pinned.some((path, index) => path !== listedSorted[index])) {
    const missing = pinned.filter(path => !listedSorted.includes(path))
    const extra = listedSorted.filter(path => !pinned.includes(path))
    throw new Error(
      `dsh-plugin-desktop: the bundled Python tree ${directory} deviates from the packaged digest `
      + `manifest at ${manifestPath} (Python v${manifest.version})`
      + (missing.length > 0 ? `; missing pinned files: ${missing.join(', ')}` : '')
      + (extra.length > 0 ? `; unexpected files: ${extra.join(', ')}` : '')
      + '; refusing to execute it — reinstall DSH Desktop',
    )
  }
  const verified = verifiedBundledPythonRuntimes.get(directory)
  if (verified !== undefined) {
    let identical = true
    for (const relativePath of pinned) {
      const identity = statFile(join(directory, relativePath))
      const fingerprint = verified.get(relativePath)
      if (fingerprint === undefined
        || fingerprint.mtimeMs !== identity.mtimeMs
        || fingerprint.size !== identity.size) {
        identical = false
        break
      }
    }
    if (identical) return
  }
  const fingerprints = new Map<string, VerifiedFileFingerprint>()
  for (const relativePath of pinned) {
    const filename = join(directory, relativePath)
    const digest = digestFile(filename)
    if (digest !== manifest.files[relativePath]) {
      throw new Error(
        `dsh-plugin-desktop: the bundled Python file ${filename} hashed to ${digest} instead of the `
        + `pinned ${manifest.files[relativePath]} (Python v${manifest.version}); `
        + 'refusing to execute it — reinstall DSH Desktop',
      )
    }
    fingerprints.set(relativePath, statFile(filename))
  }
  verifiedBundledPythonRuntimes.set(directory, fingerprints)
}

/**
 * Whether one PATH directory is a Windows Store execution-alias directory.
 *
 * Stock Windows puts `Microsoft\WindowsApps` on PATH ahead of any real
 * Python: its `python.exe` is a zero-byte store stub that opens the Microsoft
 * Store instead of running Python, so selecting it would hand the terminal
 * an alias that never executes. The match is segment-wise and
 * case-insensitive (the directory capitalization varies across installs and
 * locale directories), mirroring how the shell resolves the alias itself.
 */
function isWindowsAppsAliasDirectory(directory: string): boolean {
  return directory.split(/[\\/]/).some(segment => segment.toLowerCase() === 'windowsapps')
}

/** Find one command name on PATH without trusting a command interpreter. */
function commandOnPath(
  command: string,
  inputs: DesktopPythonRuntimeInputs,
  exists: (filename: string) => boolean,
): string | undefined {
  const environment = inputs.environment ?? process.env
  const delimiter = inputs.platform === 'win32' ? ';' : ':'
  for (const rawDirectory of inheritedPathValue(environment, inputs.platform).split(delimiter)) {
    const directory = inputs.platform === 'win32'
      && rawDirectory.startsWith('"')
      && rawDirectory.endsWith('"')
      ? rawDirectory.slice(1, -1)
      : rawDirectory
    if (directory.length === 0) continue
    // Skip the WindowsApps store stub even when it satisfies the file probe:
    // the stub exists on disk (that is how execution aliases work) but never
    // executes Python, so a later real install must win and a stub-only PATH
    // must fail loud instead of handing the terminal a dead alias.
    if (inputs.platform === 'win32' && isWindowsAppsAliasDirectory(directory)) continue
    const candidate = join(directory, command)
    if (exists(candidate)) return candidate
  }
  return undefined
}

/**
 * Resolve the Python command the desktop application exposes through its
 * `python`/`python3`/`py` aliases.
 *
 * A packaged Windows application always uses the embeddable CPython tree
 * bundled under `resources/python-runtime` and fail-loud verifies it against
 * the packaged digest manifest before handing it to a child; a packaged
 * build whose bundled tree is missing refuses the Python surface instead of
 * quietly falling back to an uncontrolled PATH lookup. An unpackaged
 * development checkout on Windows instead reuses the Python command its
 * environment already provides; other platforms bundle no Python and fail
 * loud, letting callers disable only this command surface.
 * @param moduleUrl - URL of a module emitted below the package's `lib` directory.
 * @param inputs - platform, environment, and file-probe seams.
 * @returns an absolute Python command path; never a PATH-resolved bare name.
 */
export function resolveDesktopPythonExecutable(
  moduleUrl: string,
  inputs: DesktopPythonRuntimeInputs,
): string {
  if (inputs.platform !== 'win32') {
    throw new Error(`dsh-plugin-desktop: bundled Python runtime is unsupported on ${inputs.platform}`)
  }
  const exists = inputs.exists ?? isRegularFile
  if (isPackagedModuleUrl(moduleUrl)) {
    const packaged = join(packagedBundledPythonDirectory(moduleUrl), bundledPythonCommandName())
    if (!exists(packaged)) {
      throw new Error(
        `dsh-plugin-desktop: the packaged application is missing its bundled Python command at `
        + `${packaged}; reinstall DSH Desktop`,
      )
    }
    verifyBundledPythonRuntimeIntegrity(moduleUrl, packagedBundledPythonDirectory(moduleUrl), inputs)
    return packaged
  }
  const development = commandOnPath(bundledPythonCommandName(), inputs, exists)
  if (development !== undefined) return development
  throw new Error(
    'dsh-plugin-desktop: no Python command is available; packaged Windows applications bundle one '
    + `under resources/${BUNDLED_PYTHON_DIRECTORY}, and an unpackaged development run needs `
    + 'python.exe on PATH',
  )
}

/** Marker file of pip inside the bundled tree (mirrors the staging-side constant). */
const BUNDLED_PYTHON_PIP_PACKAGE_FILE = 'Lib/site-packages/pip/__init__.py'

/** Marker file of virtualenv inside the bundled tree. */
const BUNDLED_PYTHON_VIRTUALENV_PACKAGE_FILE = 'Lib/site-packages/virtualenv/__init__.py'

/** dist-info directory pattern capturing one installed package version. */
const BUNDLED_PYTHON_DIST_INFO_PATTERN = /^Lib\/site-packages\/(pip|virtualenv)-([0-9][0-9A-Za-z.+-]*)\.dist-info\//u

/** Availability of the bundled Python tree: the pinned interpreter version
 * plus pip and virtualenv readiness inside it. */
export interface DesktopPythonPipAvailability {
  /** Pinned CPython version from the digest manifest header. */
  readonly pythonVersion: string | undefined
  /** `import pip` works inside the bundled interpreter. */
  readonly pipAvailable: boolean
  /** `import virtualenv` works inside the bundled interpreter. */
  readonly virtualenvAvailable: boolean
  /** Pinned pip version, read from the installed dist-info directory. */
  readonly pipVersion: string | undefined
  /** Pinned virtualenv version, read from the installed dist-info directory. */
  readonly virtualenvVersion: string | undefined
}

/** Frozen "nothing bundled" answer shared by every unavailable probe path. */
const PYTHON_PIP_UNAVAILABLE: DesktopPythonPipAvailability = Object.freeze({
  pythonVersion: undefined,
  pipAvailable: false,
  virtualenvAvailable: false,
  pipVersion: undefined,
  virtualenvVersion: undefined,
})

/**
 * Derive the interpreter version plus pip/virtualenv availability from one
 * digest manifest.
 *
 * The manifest lists every file of the verified tree, so a present
 * `Lib/site-packages/pip/__init__.py` marker means `import pip` works: the
 * `._pth` site unlock runs `site.main()` and puts that directory on
 * `sys.path`, and the per-file digests have already pinned the bytes. A
 * version is the dist-info directory name of the newest install (pip never
 * installs two, but the greatest name wins if it ever did).
 */
export function pipAvailabilityFromBundledPythonManifest(
  manifest: BundledPythonDigestManifest,
): DesktopPythonPipAvailability {
  const installedVersions: Record<'pip' | 'virtualenv', string[]> = { pip: [], virtualenv: [] }
  for (const relativePath of Object.keys(manifest.files)) {
    const match = BUNDLED_PYTHON_DIST_INFO_PATTERN.exec(relativePath)
    if (match === null || match[2] === undefined) continue
    installedVersions[match[1] as 'pip' | 'virtualenv'].push(match[2])
  }
  const newest = (versions: readonly string[]): string | undefined =>
    versions.reduce<string | undefined>(
      (current, candidate) => current === undefined || candidate > current ? candidate : current,
      undefined,
    )
  return Object.freeze({
    pythonVersion: manifest.version,
    pipAvailable: manifest.files[BUNDLED_PYTHON_PIP_PACKAGE_FILE] !== undefined,
    virtualenvAvailable: manifest.files[BUNDLED_PYTHON_VIRTUALENV_PACKAGE_FILE] !== undefined,
    pipVersion: newest(installedVersions.pip),
    virtualenvVersion: newest(installedVersions.virtualenv),
  })
}

/**
 * Probe whether the packaged Python runtime carries pip and virtualenv.
 *
 * A packaged-state check only: it answers from the archive-side digest
 * manifest, without spawning the interpreter. An unpackaged development
 * checkout (whose interpreter comes from the host PATH) and any unreadable
 * or malformed manifest answer the frozen "unavailable" record instead of
 * throwing — resolving and verifying the interpreter itself stays the
 * fail-loud gate, this probe merely classifies availability for callers
 * such as the python-runtime telemetry: the manifest header also names the
 * pinned CPython version, so the boot-time `python_runtime` event can stamp
 * it without spawning the interpreter.
 * @param moduleUrl - URL of a module emitted below the package's `lib` directory.
 * @param inputs - manifest-reader seam; the other seams are unused here.
 * @returns pip/virtualenv availability of the bundled tree.
 */
export function pythonPipAvailable(
  moduleUrl: string,
  inputs: DesktopPythonRuntimeInputs,
): DesktopPythonPipAvailability {
  if (!isPackagedModuleUrl(moduleUrl)) return PYTHON_PIP_UNAVAILABLE
  try {
    const readDigestManifest = inputs.readDigestManifest ?? readDigestManifestFile
    const manifest = parseBundledPythonDigestManifest(
      JSON.parse(readDigestManifest(bundledPythonDigestManifestPath(moduleUrl))) as unknown,
    )
    return pipAvailabilityFromBundledPythonManifest(manifest)
  } catch {
    return PYTHON_PIP_UNAVAILABLE
  }
}
