/** Isolated shadcn-backed Desktop dialog rendered as a modal BrowserWindow. */

import { BrowserWindow } from 'electron'
import type { MessageBoxOptions, MessageBoxReturnValue } from 'electron'
import { fileURLToPath } from 'node:url'
import {
  auxiliaryWindowChromeOptions,
  auxiliaryWindowHasCustomFrame,
} from './auxiliary-window-options.ts'
import { revealApplication } from './electron-reveal.ts'
import { DESKTOP_FRAME_HEIGHT } from './window-chrome.ts'

const DIALOG_SCHEME = 'dsh-desktop-dialog:'
const DIALOG_DOCUMENT = fileURLToPath(new URL('./native-ui/desktop-dialog.html', import.meta.url))
const MAX_BUTTONS = 4
const DIALOG_WIDTH = 480
const DIALOG_BODY_PADDING = 40
const DIALOG_CONTENT_COLUMNS = 54
const DIALOG_MESSAGE_LINE_HEIGHT = 20
const DIALOG_DETAIL_LINE_HEIGHT = 23
const DIALOG_FOOTER_GAP = 20
const DIALOG_BUTTON_HEIGHT = 32
const DIALOG_BUTTON_GAP = 8
const DIALOG_MIN_HEIGHT = 160
const DIALOG_MAX_ESTIMATED_HEIGHT = 360

export interface DesktopDialogOptions {
  readonly type?: 'none' | 'info' | 'error' | 'question' | 'warning'
  readonly title: string
  readonly message: string
  readonly detail?: string
  readonly buttons: readonly string[]
  readonly defaultId?: number
  readonly cancelId?: number
  /** Override whether this dialog exposes native close/caption controls. */
  readonly windowControls?: boolean
}

export interface DesktopDialogResult {
  readonly response: number
}

function visualColumns(value: string): number {
  return [...value].reduce((columns, character) => {
    if (character === '\t') return columns + 4
    return columns + ((character.codePointAt(0) ?? 0) > 0xff ? 2 : 1)
  }, 0)
}

function estimatedWrappedLines(value: string, maximum: number): number {
  const lines = value.split('\n').reduce((count, line) => (
    count + Math.max(1, Math.ceil(visualColumns(line) / DIALOG_CONTENT_COLUMNS))
  ), 0)
  return Math.min(maximum, Math.max(1, lines))
}

function estimatedButtonRows(buttons: readonly string[]): number {
  const availableWidth = DIALOG_WIDTH - DIALOG_BODY_PADDING
  let rows = 1
  let rowWidth = 0
  for (const label of buttons) {
    const width = Math.min(240, Math.max(52, 24 + visualColumns(label) * 7))
    const nextWidth = rowWidth === 0 ? width : rowWidth + DIALOG_BUTTON_GAP + width
    if (nextWidth > availableWidth && rowWidth !== 0) {
      rows += 1
      rowWidth = width
    } else {
      rowWidth = nextWidth
    }
  }
  return rows
}

/**
 * Keep short confirmations compact while retaining bounded room for recovery,
 * diagnostic, and multi-action dialogs. The renderer scrolls detail beyond
 * five estimated lines, so a message cannot grow a modal without limit.
 */
export function desktopDialogWindowHeight(
  options: DesktopDialogOptions,
  customFrame = false,
): number {
  const messageHeight = estimatedWrappedLines(options.message, 3) * DIALOG_MESSAGE_LINE_HEIGHT
  const detailHeight = options.detail === undefined
    ? 0
    : 8 + estimatedWrappedLines(options.detail, 5) * DIALOG_DETAIL_LINE_HEIGHT
  const contentHeight = Math.max(24, messageHeight + detailHeight)
  const buttonRows = estimatedButtonRows(options.buttons)
  const footerHeight = buttonRows * DIALOG_BUTTON_HEIGHT + (buttonRows - 1) * DIALOG_BUTTON_GAP
  const frameHeight = customFrame ? DESKTOP_FRAME_HEIGHT : 0
  const estimated = frameHeight + DIALOG_BODY_PADDING + contentHeight + DIALOG_FOOTER_GAP + footerHeight
  return Math.min(
    DIALOG_MAX_ESTIMATED_HEIGHT,
    Math.max(DIALOG_MIN_HEIGHT + frameHeight, estimated),
  )
}

function normalizedIndex(value: number | undefined, fallback: number, length: number): number {
  return value !== undefined && Number.isSafeInteger(value) && value >= 0 && value < length
    ? value
    : fallback
}

/** Parse only a bounded response generated by the local dialog document. */
export function parseDesktopDialogResponse(href: string, buttonCount: number): number | undefined {
  let url: URL
  try { url = new URL(href) } catch { return undefined }
  if (url.protocol !== DIALOG_SCHEME || url.hostname !== 'response'
    || url.username !== '' || url.password !== '' || url.port !== ''
    || url.pathname !== '' || url.hash !== ''
    || [...url.searchParams.keys()].some(key => key !== 'id')) return undefined
  const raw = url.searchParams.get('id')
  if (raw === null || !/^(?:0|[1-9]\d*)$/u.test(raw)) return undefined
  const response = Number(raw)
  return Number.isSafeInteger(response) && response >= 0 && response < buttonCount ? response : undefined
}

/** One-shot modal Desktop window; closing it always produces the cancel result. */
export class DesktopDialogWindow {
  constructor(
    private readonly options: DesktopDialogOptions,
    private readonly parent?: BrowserWindow,
  ) {}

  async run(): Promise<DesktopDialogResult> {
    if (this.options.buttons.length === 0 || this.options.buttons.length > MAX_BUTTONS) {
      throw new Error(`dsh-plugin-desktop: Desktop dialog requires 1-${String(MAX_BUTTONS)} buttons`)
    }
    const cancelId = normalizedIndex(this.options.cancelId, this.options.buttons.length - 1, this.options.buttons.length)
    const defaultId = normalizedIndex(this.options.defaultId, 0, this.options.buttons.length)
    const state = Buffer.from(JSON.stringify({
      type: this.options.type ?? 'none',
      title: this.options.title,
      message: this.options.message,
      ...(this.options.detail === undefined ? {} : { detail: this.options.detail }),
      buttons: this.options.buttons,
      defaultId,
      cancelId,
    }), 'utf8').toString('base64url')
    const parent = this.parent !== undefined && !this.parent.isDestroyed() ? this.parent : undefined
    // Parented modal dialogs are action surfaces, not independently navigable
    // windows. They stay frameless unless a caller explicitly opts into native
    // controls; standalone notices keep ordinary close controls.
    const windowControls = this.options.windowControls ?? parent === undefined
    const customFrame = auxiliaryWindowHasCustomFrame(process.platform, windowControls)
    const height = desktopDialogWindowHeight(this.options, customFrame)
    const window = new BrowserWindow({
      title: this.options.title,
      ...auxiliaryWindowChromeOptions(process.platform, windowControls),
      width: DIALOG_WIDTH,
      height,
      minWidth: 420,
      minHeight: height,
      maxWidth: 620,
      maxHeight: 440,
      resizable: windowControls,
      maximizable: false,
      fullscreenable: false,
      show: false,
      autoHideMenuBar: true,
      backgroundColor: '#202124',
      ...(parent === undefined ? {} : { parent, modal: true, skipTaskbar: true }),
      webPreferences: {
        contextIsolation: true,
        nodeIntegration: false,
        nodeIntegrationInSubFrames: false,
        sandbox: true,
        webSecurity: true,
        webviewTag: false,
        spellcheck: false,
        partition: 'dsh-desktop-dialog',
      },
    })
    window.accessibleTitle = this.options.title
    window.removeMenu()
    window.webContents.setWindowOpenHandler(() => ({ action: 'deny' }))
    window.webContents.on('will-attach-webview', event => { event.preventDefault() })

    return await new Promise<DesktopDialogResult>((resolve, reject) => {
      let settled = false
      const finish = (response: number): void => {
        if (settled) return
        settled = true
        if (!window.isDestroyed()) window.destroy()
        resolve(Object.freeze({ response }))
      }
      const navigate = (event: Electron.Event, href: string): void => {
        event.preventDefault()
        const response = parseDesktopDialogResponse(href, this.options.buttons.length)
        if (response !== undefined) finish(response)
      }
      window.webContents.on('will-navigate', navigate)
      window.webContents.on('will-redirect', navigate)
      window.once('ready-to-show', () => { revealApplication(window) })
      window.on('closed', () => { finish(cancelId) })
      void window.loadFile(DIALOG_DOCUMENT, {
        query: {
          state,
          platform: process.platform,
          frame: String(customFrame),
        },
      }).catch((cause: unknown) => {
        if (settled) return
        settled = true
        if (!window.isDestroyed()) window.destroy()
        reject(cause)
      })
    })
  }
}

/** Render a Desktop-level modal window instead of an in-page overlay. */
export async function showDesktopDialog(
  options: DesktopDialogOptions,
  parent?: BrowserWindow,
): Promise<DesktopDialogResult> {
  return await new DesktopDialogWindow(options, parent).run()
}

/** Electron MessageBox-compatible adapter backed by the Desktop dialog window. */
export async function showDesktopMessageBox(
  options: MessageBoxOptions,
  parent?: BrowserWindow,
): Promise<MessageBoxReturnValue> {
  const result = await showDesktopDialog({
    type: options.type ?? 'none',
    title: options.title ?? 'DSH Desktop',
    message: options.message,
    ...(options.detail === undefined ? {} : { detail: options.detail }),
    buttons: options.buttons ?? ['OK'],
    ...(options.defaultId === undefined ? {} : { defaultId: options.defaultId }),
    ...(options.cancelId === undefined ? {} : { cancelId: options.cancelId }),
  }, parent)
  return Object.freeze({ response: result.response, checkboxChecked: false })
}
