/**
 * Company LLM gateway: obfuscated-blob decoding and the managed-model wiring
 * decision helpers used by the launcher composition and boot.
 *
 * The gateway facts (per-provider route, display name, credential
 * environment name, base URL, api key, and model list) ship as one
 * obfuscated blob generated by `scripts/make-model-gateway-blob.mjs`.
 * Obfuscation is not encryption — see the generator header for the
 * signed-off soft-barrier positioning; the decode below is the runtime peer
 * of that encoder. Route, display name, and credential environment name are
 * blob data, not code constants, so adding a provider (a second gateway
 * key, a renamed route) is a regeneration, never a code change; the pin
 * tests in tests/model-gateway.spec.ts assert the exact literals against
 * the decoded committed blob so a regeneration cannot silently drift.
 *
 * Everything here is inert unless the embedded policy is `locked` with
 * `managedModels: true`: an open or unlocked build never decodes the blob,
 * never injects a gateway credential, and never registers a provider.
 *
 * @module dsh-plugin-desktop/model-gateway
 */

import { readFileSync } from 'node:fs'
import {
  parseCredentialsDocument,
  resolveSpec,
} from '@deepseek-ai/dsh-credentials-local'
import { type DesktopPolicy } from './desktop-policy.ts'
import { MODEL_GATEWAY_BLOB } from './model-gateway-blob.ts'

/** Loader row id of the pi-ai multi-provider adapter the company route joins. */
export const LLM_PI_AI_ROW_ID = 'llm-pi-ai'
/** Loader row id of the native DeepSeek adapter whose built-in catalog managed builds hide. */
export const LLM_DEEPSEEK_ROW_ID = 'llm-deepseek'
/** Loader row id of the agent default-model selection restated by managed builds. */
export const AGENT_DEFAULT_MODEL_ROW_ID = 'agent-default-model'
/** Loader row id of the web Models settings page hidden by managed builds. */
export const UI_SETTINGS_MODELS_ROW_ID = 'ui-settings-models'

/**
 * Fixed XOR key. NOT a secret: it must stay byte-identical to
 * `scripts/make-model-gateway-blob.mjs` or the decode fails loudly.
 */
const OBFUSCATION_KEY = 'dsh-desktop-model-gateway-obfuscation-key-v1'

/** One served model: the wire id plus optional overrides. */
export interface CompanyModelGatewayModel {
  /** Model id sent to the gateway wire; the telemetry model column. */
  readonly id: string
  /** Display name for selectors; the id displays when absent. */
  readonly name?: string
  /** Maximum combined request and response context in tokens; the upstream route default applies when absent. */
  readonly contextWindow?: number
  /** Maximum output tokens; the upstream route default applies when absent. */
  readonly maxTokens?: number
}

/** One managed provider decoded from the blob. */
export interface CompanyModelGatewayProvider {
  /** Registered provider route (the settings dict key and telemetry provider id). */
  readonly route: string
  /** Display name for the provider on configuration surfaces. */
  readonly displayName: string
  /** `DSH_`-prefixed environment variable carrying this provider's api key. */
  readonly apiKeyEnv: string
  /** Bare https base URL of the OpenAI-compatible gateway. */
  readonly baseUrl: string
  /** Gateway api key (bearer token); never leaves memory or the environment. */
  readonly apiKey: string
  /** Served models in catalog order. */
  readonly models: readonly CompanyModelGatewayModel[]
}

/** Decoded company model gateway facts, one entry per managed provider. */
export interface CompanyModelGateway {
  /** Managed providers in pinned order; the first model of the first provider is the default. */
  readonly providers: readonly CompanyModelGatewayProvider[]
}

function invalidBlob(message: string): Error {
  return new Error(`dsh-plugin-desktop: invalid model gateway blob: ${message}`)
}

/** Sorted key set every provider entry must carry, exactly. */
const PROVIDER_KEYS = Object.freeze(['apiKey', 'apiKeyEnv', 'baseUrl', 'displayName', 'models', 'route'])

/** Every key a model entry may carry; `id` is the only required one. */
const MODEL_KEYS = Object.freeze(['id', 'name', 'contextWindow', 'maxTokens'])

/** apiKeyEnv shape: `DSH_`-prefixed so `.env` layers reject it and masks see it. */
const API_KEY_ENV_PATTERN = /^DSH_[A-Z][A-Z0-9_]*$/u

function sameKeys(keys: readonly string[], expected: readonly string[]): boolean {
  return keys.length === expected.length && expected.every((name, index) => keys[index] === name)
}

/**
 * Decode and strictly validate one obfuscated gateway blob. The validation
 * mirrors the generator (`scripts/make-model-gateway-blob.mjs`) on purpose:
 * a payload the generator accepts must always decode here, and both reject
 * the retired single-provider v1 shape with a pointer to regeneration.
 * @param blob - base64 XOR-obfuscated JSON payload.
 * @returns the validated gateway facts, deeply frozen.
 * @throws when the blob is malformed; the message never includes blob content.
 */
export function decodeModelGatewayBlob(blob: string): CompanyModelGateway {
  if (typeof blob !== 'string' || blob.length === 0) {
    throw invalidBlob('the blob must be a non-empty string')
  }
  let cipher: Buffer
  try {
    cipher = Buffer.from(blob, 'base64')
  } catch (cause) {
    throw invalidBlob(`base64 decoding failed: ${cause instanceof Error ? cause.message : String(cause)}`)
  }
  const key = Buffer.from(OBFUSCATION_KEY, 'utf8')
  const plain = Buffer.from(cipher)
  for (let index = 0; index < plain.length; index += 1) {
    plain[index] = plain[index]! ^ key[index % key.length]!
  }
  let document: unknown
  try {
    document = JSON.parse(plain.toString('utf8')) as unknown
  } catch {
    throw invalidBlob('the decoded payload is not valid JSON')
  }
  if (typeof document !== 'object' || document === null || Array.isArray(document)) {
    throw invalidBlob('the decoded payload must be an object')
  }
  const keys = Object.keys(document).sort()
  if (keys.length === 3 && keys[0] === 'apiKey' && keys[1] === 'baseUrl' && keys[2] === 'models') {
    throw invalidBlob(
      'the decoded payload is the retired single-provider v1 shape; regenerate the blob with '
        + 'scripts/make-model-gateway-blob.mjs reading DSH_GATEWAY_PROVIDERS_JSON',
    )
  }
  if (keys.length !== 1 || keys[0] !== 'providers') {
    throw invalidBlob('the decoded payload must carry exactly providers')
  }
  const { providers } = document as Record<string, unknown>
  if (!Array.isArray(providers) || providers.length === 0) {
    throw invalidBlob('providers must be a non-empty array')
  }
  const routes = new Set<string>()
  const apiKeyEnvs = new Set<string>()
  const decoded: CompanyModelGatewayProvider[] = []
  for (const [index, entry] of providers.entries()) {
    const site = `providers[${String(index)}]`
    if (typeof entry !== 'object' || entry === null || Array.isArray(entry)) {
      throw invalidBlob(`${site} must be an object`)
    }
    if (!sameKeys(Object.keys(entry).sort(), PROVIDER_KEYS)) {
      throw invalidBlob(`${site} must carry exactly route, displayName, apiKeyEnv, baseUrl, apiKey, and models`)
    }
    const { route, displayName, apiKeyEnv, baseUrl, apiKey, models } = entry as Record<string, unknown>
    if (typeof route !== 'string' || route.length === 0) {
      throw invalidBlob(`${site}.route must be a non-empty string`)
    }
    if (routes.has(route)) throw invalidBlob(`provider route "${route}" is listed more than once`)
    routes.add(route)
    if (typeof displayName !== 'string' || displayName.length === 0) {
      throw invalidBlob(`${site}.displayName must be a non-empty string`)
    }
    if (typeof apiKeyEnv !== 'string' || !API_KEY_ENV_PATTERN.test(apiKeyEnv)) {
      throw invalidBlob(`${site}.apiKeyEnv must be a DSH_-prefixed environment name (uppercase letters, digits, underscores)`)
    }
    if (apiKeyEnvs.has(apiKeyEnv)) throw invalidBlob(`apiKeyEnv "${apiKeyEnv}" is listed more than once`)
    apiKeyEnvs.add(apiKeyEnv)
    if (typeof baseUrl !== 'string' || baseUrl.length === 0) {
      throw invalidBlob(`${site}.baseUrl must be a non-empty https base URL`)
    }
    let url: URL
    try {
      url = new URL(baseUrl)
    } catch {
      throw invalidBlob(`${site}.baseUrl must be a parseable URL`)
    }
    if (url.protocol !== 'https:' || url.username !== '' || url.password !== '') {
      throw invalidBlob(`${site}.baseUrl must be a bare https URL`)
    }
    if (typeof apiKey !== 'string' || apiKey.length === 0) {
      throw invalidBlob(`${site}.apiKey must be a non-empty string`)
    }
    if (!Array.isArray(models) || models.length === 0) {
      throw invalidBlob(`${site}.models must be a non-empty array`)
    }
    const modelIds = new Set<string>()
    const decodedModels: CompanyModelGatewayModel[] = []
    for (const [modelIndex, modelEntry] of models.entries()) {
      const modelSite = `${site}.models[${String(modelIndex)}]`
      if (typeof modelEntry !== 'object' || modelEntry === null || Array.isArray(modelEntry)) {
        throw invalidBlob(`${modelSite} must be an object`)
      }
      const modelKeys = Object.keys(modelEntry)
      if (!modelKeys.includes('id') || modelKeys.some(name => !MODEL_KEYS.includes(name))) {
        throw invalidBlob(`${modelSite} must carry exactly id, with optional name, contextWindow, and maxTokens`)
      }
      const { id, name, contextWindow, maxTokens } = modelEntry as Record<string, unknown>
      if (typeof id !== 'string' || id.length === 0) {
        throw invalidBlob(`${modelSite}.id must be a non-empty string`)
      }
      if (modelIds.has(id)) throw invalidBlob(`model "${id}" is listed more than once under provider "${route}"`)
      modelIds.add(id)
      if (name !== undefined && (typeof name !== 'string' || name.length === 0)) {
        throw invalidBlob(`${modelSite}.name must be a non-empty string when present`)
      }
      // Capacities are optional: absent means the upstream route defaults
      // apply (catalog.ts falls back to defaultContextWindow/defaultMaxTokens).
      // Present values must already satisfy upstream's own positive-integer
      // rule so a decoded blob can never compose into an invalid route.
      for (const [field, value] of [['contextWindow', contextWindow], ['maxTokens', maxTokens]] as const) {
        if (value !== undefined && (typeof value !== 'number' || !Number.isInteger(value) || value <= 0)) {
          throw invalidBlob(`${modelSite}.${field} must be a positive integer when present`)
        }
      }
      decodedModels.push(Object.freeze({
        id,
        ...(name === undefined ? {} : { name }),
        ...(contextWindow === undefined ? {} : { contextWindow }),
        ...(maxTokens === undefined ? {} : { maxTokens }),
      } as CompanyModelGatewayModel))
    }
    decoded.push(Object.freeze({
      route,
      displayName,
      apiKeyEnv,
      baseUrl,
      apiKey,
      models: Object.freeze(decodedModels),
    }))
  }
  return Object.freeze({ providers: Object.freeze(decoded) })
}

/**
 * Decode the embedded gateway blob when — and only when — the policy pins the
 * managed-model posture (`locked` && `managedModels`). Every other policy
 * keeps the blob unread and the build fully native.
 * @param policy - embedded desktop policy; omitted or unlocked policies stay inert.
 * @param blob - blob override for tests; defaults to the embedded constant.
 * @returns the gateway facts, or undefined for every unmanaged build.
 * @throws when a managed build carries a corrupt blob (fail closed).
 */
export function managedModelGateway(
  policy: DesktopPolicy | undefined,
  blob: string = MODEL_GATEWAY_BLOB,
): CompanyModelGateway | undefined {
  if (policy?.locked !== true || policy.managedModels !== true) return undefined
  return decodeModelGatewayBlob(blob)
}

/**
 * Environment name the company agent preset's managed-models gate evaluates:
 * a dedicated preset-gate name, deliberately separate from every CLI policy
 * hand-off key (`DESKTOP_POLICY_ENVIRONMENT`). The hand-off carries the RAW
 * `managedModels` flag as one member of an all-five group that
 * `desktopPolicyFromEnvironment` refuses to decode partially, while this
 * gate encodes the EFFECTIVE posture below — one shared name would blur two
 * facts and leave a lone hand-off-shaped key sitting in the shared host
 * environment, poison for any future consumer reading the hand-off from a
 * host snapshot. The `DSH_` prefix keeps this launcher-owned name under the
 * same protections as the other `DSH_*` names: scrubbed out of login-shell
 * captures and rejected by `.env` layers.
 */
export const PRESET_MANAGED_MODELS_GATE = 'DSH_COMPANY_MANAGED_MODELS'

/**
 * The process-environment entry the company agent preset's managed-models
 * gate reads. The Deloitte preset's `tool-web` row carries a `!!js` disabled
 * expression over {@link PRESET_MANAGED_MODELS_GATE} exactly (web search
 * rides api.deepseek.com with `DEEPSEEK_API_KEY`, a credential managed users
 * do not hold), and Loader expressions evaluate in the Host process — so the
 * launcher must write the value into `process.env` before the Host
 * composition loads the preset.
 *
 * The value pins the EFFECTIVE managed posture — `locked` && `managedModels`
 * — and every other build resolves to `'0'`: the launcher writes the entry
 * unconditionally, so an open, unlocked, or development build both evaluates
 * the gate to false and scrubs any stray inherited `'1'`, restoring the
 * native enabled tool exactly as upstream ships it.
 * @param policy - embedded desktop policy of this launch.
 * @returns the environment name and value to write before Host composition.
 */
export function managedModelsPresetGateEntry(
  policy: DesktopPolicy,
): Readonly<{ readonly name: string, readonly value: string }> {
  return {
    name: PRESET_MANAGED_MODELS_GATE,
    value: policy.locked && policy.managedModels ? '1' : '0',
  }
}

/** The `llm-pi-ai` provider profile a managed build registers in memory. */
export interface CompanyModelGatewayProviderProfile {
  /** Selector label. */
  readonly displayName: string
  /** Credential reference resolved per request through the credentials seam. */
  readonly apiKeyEnv: string
  /** OpenAI-compatible wire protocol (the gateway is chat-completions shaped). */
  readonly api: 'openai-completions'
  /** Gateway endpoint. */
  readonly baseURL: string
  /** Served models; unspecified capabilities fall back to the route defaults the adapter owns. */
  readonly models: readonly CompanyModelGatewayModel[]
}

/**
 * Render the composition-layer `llm-pi-ai` provider profile for one managed
 * gateway provider. The gateway's `/models` endpoint is absent (404), so the
 * model list is exactly the blob's list — no dynamic discovery is attempted.
 * Each model entry passes through its optional display name and capacities
 * (upstream `catalog.ts` consumes exactly `name`, `contextWindow`, and
 * `maxTokens` off a profile model, falling back to the route defaults for
 * whatever is absent). The response is a reasoning-model format regardless
 * of request configuration, so the profile declares no reasoning-effort
 * levels: the harness surfaces the returned reasoning content without
 * asking the gateway to think.
 * @param provider - one decoded provider from the company gateway blob.
 * @returns the provider profile pinned into the composition base layer.
 */
export function companyModelGatewayProviderProfile(
  provider: CompanyModelGatewayProvider,
): CompanyModelGatewayProviderProfile {
  return {
    displayName: provider.displayName,
    apiKeyEnv: provider.apiKeyEnv,
    api: 'openai-completions',
    baseURL: provider.baseUrl,
    models: provider.models.map(({ id, name, contextWindow, maxTokens }) => ({
      id,
      ...(name === undefined ? {} : { name }),
      ...(contextWindow === undefined ? {} : { contextWindow }),
      ...(maxTokens === undefined ? {} : { maxTokens }),
    })),
  }
}

/**
 * The default model selection a managed build pins: the first provider's
 * first listed model (the generator writes the pinned default first).
 * @param gateway - decoded company gateway facts.
 * @returns the `agent-default-model` row config values.
 */
export function companyModelGatewayDefaultModel(
  gateway: CompanyModelGateway,
): { readonly provider: string, readonly model: string } {
  const provider = gateway.providers[0]
  if (provider === undefined) throw invalidBlob('the provider list is empty')
  const model = provider.models[0]
  if (model === undefined) throw invalidBlob(`provider "${provider.route}" carries no models`)
  return { provider: provider.route, model: model.id }
}

/** Result of the read-only probe over the managed credentials document. */
export type StoredCredentialNames =
  | { readonly status: 'ok'; readonly names: ReadonlySet<string> }
  | { readonly status: 'unreadable'; readonly reason: string }

/**
 * Read-only probe of the credentials document the upstream
 * `dsh-credentials-local` provider owns, parsed with that package's own
 * strict parser so the yield decision uses the store's real semantics
 * instead of an invented reader. Nothing is written; values are never read
 * out — membership in `refs` is the whole question.
 * @param credentialsPath - absolute path of `.credentials.yaml`.
 * @returns the stored reference names, or why the store could not be read.
 */
export function readStoredCredentialNames(credentialsPath: string): StoredCredentialNames {
  let text: string
  try {
    text = readFileSync(credentialsPath, 'utf8')
  } catch (cause) {
    const code = (cause as NodeJS.ErrnoException | null)?.code
    if (code === 'ENOENT') return { status: 'ok', names: new Set() }
    return {
      status: 'unreadable',
      reason: `the credentials document at ${credentialsPath} is unreadable: ${code ?? (cause instanceof Error ? cause.message : String(cause))}`,
    }
  }
  try {
    return { status: 'ok', names: new Set(parseCredentialsDocument(text, credentialsPath).refs.keys()) }
  } catch (cause) {
    return {
      status: 'unreadable',
      reason: cause instanceof Error ? cause.message : String(cause),
    }
  }
}

/** Inputs of the managed-mode environment injection decision. */
export interface ManagedModelGatewayEnvironmentProbe {
  /**
   * The inherited process environment. Each provider's {@link
   * CompanyModelGatewayProvider.apiKeyEnv} is looked up here; an empty string
   * counts as unset, mirroring how the upstream credentials seam treats the
   * environment layer.
   */
  readonly inheritedEnvironment: Readonly<Record<string, string | undefined>>
  /** Read-only probe of the managed credentials document. */
  readonly storedCredentials: StoredCredentialNames
}

/** Why one provider's launcher credential was — or was not — injected. */
export type ManagedModelGatewayProviderEnvironmentReason =
  | 'injected'
  | 'user-environment'
  | 'user-credentials'
  | 'unreadable-credential-store'

/** Decision for one provider's credential environment entry. */
export interface ManagedModelGatewayProviderEnvironmentDecision {
  /** The provider the decision belongs to. */
  readonly route: string
  /** The environment name the decision is about. */
  readonly apiKeyEnv: string
  /** Whether the launcher writes its own value for {@link apiKeyEnv}. */
  readonly inject: boolean
  readonly reason: ManagedModelGatewayProviderEnvironmentReason
}

/** Decision of {@link resolveManagedModelGatewayEnvironment}. */
export type ManagedModelGatewayEnvironmentDecision =
  | { readonly managed: false, readonly reason: 'unmanaged-build' }
  | {
    readonly managed: true
    /** The exact environment entries to write: one per provider that passed the yield checks. */
    readonly environment: Readonly<Record<string, string>>
    /** Per-provider outcomes, blob order. */
    readonly providers: readonly ManagedModelGatewayProviderEnvironmentDecision[]
  }

/**
 * Decide which gateway credentials this launch injects into the process
 * environment — one decision per provider, each honoring the same
 * user-priority yield semantics the single-provider era defined:
 *
 * - the inherited environment already carries the provider's variable (the
 *   layer `credentials-local` trusts most and treats as read-only), or
 * - the user already stored that reference in `.credentials.yaml`
 *   (the layer the Models page writes),
 *
 * then the user's own configuration wins and this launcher injects nothing
 * for that provider — independently of every other provider. A `.env` file
 * cannot carry these names (upstream rejects `DSH_*` names there), so no
 * third case exists. An unreadable credentials store yields for every
 * provider: the upstream provider will surface that failure on its own load
 * path, and a half-informed injection could not be trusted to lose to a
 * layer it could not read.
 * @param gateway - decoded company gateway facts; undefined for unmanaged builds.
 * @param probe - yield-decision inputs.
 * @returns the per-provider injection decisions plus the exact environment
 * entries to write.
 */
export function resolveManagedModelGatewayEnvironment(
  gateway: CompanyModelGateway | undefined,
  probe: ManagedModelGatewayEnvironmentProbe,
): ManagedModelGatewayEnvironmentDecision {
  if (gateway === undefined) return { managed: false, reason: 'unmanaged-build' }
  const unreadable = probe.storedCredentials.status === 'unreadable'
  const storedNames = unreadable ? undefined : probe.storedCredentials.names
  const decisions = gateway.providers.map((provider): ManagedModelGatewayProviderEnvironmentDecision => {
    const inherited = probe.inheritedEnvironment[provider.apiKeyEnv]
    if ((inherited ?? '').length > 0) {
      return { route: provider.route, apiKeyEnv: provider.apiKeyEnv, inject: false, reason: 'user-environment' }
    }
    if (unreadable) {
      return { route: provider.route, apiKeyEnv: provider.apiKeyEnv, inject: false, reason: 'unreadable-credential-store' }
    }
    if (storedNames?.has(provider.apiKeyEnv) === true) {
      return { route: provider.route, apiKeyEnv: provider.apiKeyEnv, inject: false, reason: 'user-credentials' }
    }
    return { route: provider.route, apiKeyEnv: provider.apiKeyEnv, inject: true, reason: 'injected' }
  })
  const environment: Record<string, string> = {}
  for (const [index, decision] of decisions.entries()) {
    if (decision.inject) environment[decision.apiKeyEnv] = gateway.providers[index]!.apiKey
  }
  return { managed: true, environment, providers: decisions }
}

/**
 * Resolve the credentials document path the same way the upstream provider
 * does, so the probe and the provider can never disagree about the file.
 * @param home - Harness home directory.
 * @returns the absolute `.credentials.yaml` path.
 */
export function storedCredentialsPath(home: string): string {
  return resolveSpec({ dshHome: home }).filename
}
