/**
 * Company LLM gateway: obfuscated-blob decoding and the managed-model wiring
 * decision helpers used by the launcher composition and boot.
 *
 * The gateway facts (per-provider route, display name, credential
 * environment name, base URL, api key, and model list) ship as one
 * obfuscated blob generated by `scripts/make-model-gateway-blob.mjs`.
 * Obfuscation is not encryption — see the generator header for the
 * signed-off soft-barrier positioning; the decode below is the runtime peer
 * of that encoder. Route, display name, and credential environment name are
 * blob data, not code constants, so adding a provider (a second gateway
 * key, a renamed route) is a regeneration, never a code change; the pin
 * tests in tests/model-gateway.spec.ts assert the exact literals against
 * the decoded committed blob so a regeneration cannot silently drift.
 *
 * Everything here is inert unless the embedded policy is `locked` with
 * `managedModels: true`: an open or unlocked build never decodes the blob,
 * never injects a gateway credential, and never registers a provider.
 *
 * @module dsh-plugin-desktop/model-gateway
 */

import { readFileSync } from 'node:fs'
import {
  parseCredentialsDocument,
  resolveSpec,
} from '@deepseek-ai/dsh-credentials-local'
import { type DesktopPolicy } from './desktop-policy.ts'
import { MODEL_GATEWAY_BLOB } from './model-gateway-blob.ts'

/** Loader row id of the pi-ai multi-provider adapter the company route joins. */
export const LLM_PI_AI_ROW_ID = 'llm-pi-ai'
/** Loader row id of the native DeepSeek adapter whose built-in catalog managed builds hide. */
export const LLM_DEEPSEEK_ROW_ID = 'llm-deepseek'
/** Loader row id of the agent default-model selection restated by managed builds. */
export const AGENT_DEFAULT_MODEL_ROW_ID = 'agent-default-model'
/** Loader row id of the web Models settings page hidden by managed builds. */
export const UI_SETTINGS_MODELS_ROW_ID = 'ui-settings-models'

/**
 * Fixed XOR key. NOT a secret: it must stay byte-identical to
 * `scripts/make-model-gateway-blob.mjs` or the decode fails loudly.
 */
const OBFUSCATION_KEY = 'dsh-desktop-model-gateway-obfuscation-key-v1'

/** One served model: the wire id plus optional overrides. */
export interface CompanyModelGatewayModel {
  /** Model id sent to the gateway wire; the telemetry model column. */
  readonly id: string
  /** Display name for selectors; the id displays when absent. */
  readonly name?: string
  /** Maximum combined request and response context in tokens; the upstream route default applies when absent. */
  readonly contextWindow?: number
  /** Maximum output tokens; the upstream route default applies when absent. */
  readonly maxTokens?: number
  /**
   * Request modalities the endpoint accepts ('text' and/or 'image'; the
   * pi-ai modality set). A hand-declared model states none by default, so a
   * multimodal model must declare `['text', 'image']` or image attachments
   * never reach it — declaring is a claim about the endpoint, not a check.
   */
  readonly input?: readonly CompanyModelGatewayModality[]
}

/** Every modality a blob model may declare (mirrors the pi-ai set). */
export type CompanyModelGatewayModality = 'text' | 'image'

/** One managed provider decoded from the blob. */
export interface CompanyModelGatewayProvider {
  /** Registered provider route (the settings dict key and telemetry provider id). */
  readonly route: string
  /** Display name for the provider on configuration surfaces. */
  readonly displayName: string
  /** `DSH_`-prefixed environment variable carrying this provider's api key. */
  readonly apiKeyEnv: string
  /** Bare https base URL of the OpenAI-compatible gateway. */
  readonly baseUrl: string
  /** Gateway api key (bearer token); never leaves memory or the environment. */
  readonly apiKey: string
  /** Served models in catalog order. */
  readonly models: readonly CompanyModelGatewayModel[]
}

/** Decoded company model gateway facts, one entry per managed provider. */
export interface CompanyModelGateway {
  /** Managed providers in pinned order; the first model of the first provider is the default. */
  readonly providers: readonly CompanyModelGatewayProvider[]
}

function invalidBlob(message: string): Error {
  return new Error(`dsh-plugin-desktop: invalid model gateway blob: ${message}`)
}

/** Sorted key set every provider entry must carry, exactly. */
const PROVIDER_KEYS = Object.freeze(['apiKey', 'apiKeyEnv', 'baseUrl', 'displayName', 'models', 'route'])

/** Every key a model entry may carry; `id` is the only required one. */
const MODEL_KEYS = Object.freeze(['id', 'name', 'contextWindow', 'maxTokens', 'input'])

/** apiKeyEnv shape: `DSH_`-prefixed so `.env` layers reject it and masks see it. */
const API_KEY_ENV_PATTERN = /^DSH_[A-Z][A-Z0-9_]*$/u

function sameKeys(keys: readonly string[], expected: readonly string[]): boolean {
  return keys.length === expected.length && expected.every((name, index) => keys[index] === name)
}

/**
 * Decode and strictly validate one obfuscated gateway blob. The validation
 * mirrors the generator (`scripts/make-model-gateway-blob.mjs`) on purpose:
 * a payload the generator accepts must always decode here, and both reject
 * the retired single-provider v1 shape with a pointer to regeneration.
 * @param blob - base64 XOR-obfuscated JSON payload.
 * @returns the validated gateway facts, deeply frozen.
 * @throws when the blob is malformed; the message never includes blob content.
 */
export function decodeModelGatewayBlob(blob: string): CompanyModelGateway {
  if (typeof blob !== 'string' || blob.length === 0) {
    throw invalidBlob('the blob must be a non-empty string')
  }
  let cipher: Buffer
  try {
    cipher = Buffer.from(blob, 'base64')
  } catch (cause) {
    throw invalidBlob(`base64 decoding failed: ${cause instanceof Error ? cause.message : String(cause)}`)
  }
  const key = Buffer.from(OBFUSCATION_KEY, 'utf8')
  const plain = Buffer.from(cipher)
  for (let index = 0; index < plain.length; index += 1) {
    plain[index] = plain[index]! ^ key[index % key.length]!
  }
  let document: unknown
  try {
    document = JSON.parse(plain.toString('utf8')) as unknown
  } catch {
    throw invalidBlob('the decoded payload is not valid JSON')
  }
  if (typeof document !== 'object' || document === null || Array.isArray(document)) {
    throw invalidBlob('the decoded payload must be an object')
  }
  const keys = Object.keys(document).sort()
  if (keys.length === 3 && keys[0] === 'apiKey' && keys[1] === 'baseUrl' && keys[2] === 'models') {
    throw invalidBlob(
      'the decoded payload is the retired single-provider v1 shape; regenerate the blob with '
        + 'scripts/make-model-gateway-blob.mjs reading DSH_GATEWAY_PROVIDERS_JSON',
    )
  }
  if (keys.length !== 1 || keys[0] !== 'providers') {
    throw invalidBlob('the decoded payload must carry exactly providers')
  }
  const { providers } = document as Record<string, unknown>
  if (!Array.isArray(providers) || providers.length === 0) {
    throw invalidBlob('providers must be a non-empty array')
  }
  const routes = new Set<string>()
  const apiKeyEnvs = new Set<string>()
  const decoded: CompanyModelGatewayProvider[] = []
  for (const [index, entry] of providers.entries()) {
    const site = `providers[${String(index)}]`
    if (typeof entry !== 'object' || entry === null || Array.isArray(entry)) {
      throw invalidBlob(`${site} must be an object`)
    }
    if (!sameKeys(Object.keys(entry).sort(), PROVIDER_KEYS)) {
      throw invalidBlob(`${site} must carry exactly route, displayName, apiKeyEnv, baseUrl, apiKey, and models`)
    }
    const { route, displayName, apiKeyEnv, baseUrl, apiKey, models } = entry as Record<string, unknown>
    if (typeof route !== 'string' || route.length === 0) {
      throw invalidBlob(`${site}.route must be a non-empty string`)
    }
    if (routes.has(route)) throw invalidBlob(`provider route "${route}" is listed more than once`)
    routes.add(route)
    if (typeof displayName !== 'string' || displayName.length === 0) {
      throw invalidBlob(`${site}.displayName must be a non-empty string`)
    }
    if (typeof apiKeyEnv !== 'string' || !API_KEY_ENV_PATTERN.test(apiKeyEnv)) {
      throw invalidBlob(`${site}.apiKeyEnv must be a DSH_-prefixed environment name (uppercase letters, digits, underscores)`)
    }
    if (apiKeyEnvs.has(apiKeyEnv)) throw invalidBlob(`apiKeyEnv "${apiKeyEnv}" is listed more than once`)
    apiKeyEnvs.add(apiKeyEnv)
    if (typeof baseUrl !== 'string' || baseUrl.length === 0) {
      throw invalidBlob(`${site}.baseUrl must be a non-empty https base URL`)
    }
    let url: URL
    try {
      url = new URL(baseUrl)
    } catch {
      throw invalidBlob(`${site}.baseUrl must be a parseable URL`)
    }
    if (url.protocol !== 'https:' || url.username !== '' || url.password !== '') {
      throw invalidBlob(`${site}.baseUrl must be a bare https URL`)
    }
    if (typeof apiKey !== 'string' || apiKey.length === 0) {
      throw invalidBlob(`${site}.apiKey must be a non-empty string`)
    }
    if (!Array.isArray(models) || models.length === 0) {
      throw invalidBlob(`${site}.models must be a non-empty array`)
    }
    const modelIds = new Set<string>()
    const decodedModels: CompanyModelGatewayModel[] = []
    for (const [modelIndex, modelEntry] of models.entries()) {
      const modelSite = `${site}.models[${String(modelIndex)}]`
      if (typeof modelEntry !== 'object' || modelEntry === null || Array.isArray(modelEntry)) {
        throw invalidBlob(`${modelSite} must be an object`)
      }
      const modelKeys = Object.keys(modelEntry)
      if (!modelKeys.includes('id') || modelKeys.some(name => !MODEL_KEYS.includes(name))) {
        throw invalidBlob(`${modelSite} must carry exactly id, with optional name, contextWindow, maxTokens, and input`)
      }
      const { id, name, contextWindow, maxTokens, input } = modelEntry as Record<string, unknown>
      if (typeof id !== 'string' || id.length === 0) {
        throw invalidBlob(`${modelSite}.id must be a non-empty string`)
      }
      if (modelIds.has(id)) throw invalidBlob(`model "${id}" is listed more than once under provider "${route}"`)
      modelIds.add(id)
      if (name !== undefined && (typeof name !== 'string' || name.length === 0)) {
        throw invalidBlob(`${modelSite}.name must be a non-empty string when present`)
      }
      // Capacities are optional: absent means the upstream route defaults
      // apply (catalog.ts falls back to defaultContextWindow/defaultMaxTokens).
      // Present values must already satisfy upstream's own positive-integer
      // rule so a decoded blob can never compose into an invalid route.
      for (const [field, value] of [['contextWindow', contextWindow], ['maxTokens', maxTokens]] as const) {
        if (value !== undefined && (typeof value !== 'number' || !Number.isInteger(value) || value <= 0)) {
          throw invalidBlob(`${modelSite}.${field} must be a positive integer when present`)
        }
      }
      // Modalities are optional: absent keeps the hand-declared text-only
      // default (a model outside the installed catalog states no answer).
      if (input !== undefined) {
        if (!Array.isArray(input) || input.length === 0 || input.some(m => m !== 'text' && m !== 'image')) {
          throw invalidBlob(`${modelSite}.input must be a non-empty array of 'text'/'image' when present`)
        }
        if (new Set(input).size !== input.length) {
          throw invalidBlob(`${modelSite}.input must not repeat a modality`)
        }
      }
      decodedModels.push(Object.freeze({
        id,
        ...(name === undefined ? {} : { name }),
        ...(contextWindow === undefined ? {} : { contextWindow }),
        ...(maxTokens === undefined ? {} : { maxTokens }),
        ...(input === undefined ? {} : { input: [...input] as CompanyModelGatewayModality[] }),
      } as unknown as CompanyModelGatewayModel))
    }
    decoded.push(Object.freeze({
      route,
      displayName,
      apiKeyEnv,
      baseUrl,
      apiKey,
      models: Object.freeze(decodedModels),
    }))
  }
  return Object.freeze({ providers: Object.freeze(decoded) })
}

/**
 * Decode the embedded gateway blob when — and only when — the policy pins the
 * managed-model posture (`locked` && `managedModels`). Every other policy
 * keeps the blob unread and the build fully native.
 * @param policy - embedded desktop policy; omitted or unlocked policies stay inert.
 * @param blob - blob override for tests; defaults to the embedded constant.
 * @returns the gateway facts, or undefined for every unmanaged build.
 * @throws when a managed build carries a corrupt blob (fail closed).
 */
export function managedModelGateway(
  policy: DesktopPolicy | undefined,
  blob: string = MODEL_GATEWAY_BLOB,
): CompanyModelGateway | undefined {
  if (policy?.locked !== true || policy.managedModels !== true) return undefined
  return decodeModelGatewayBlob(blob)
}

/**
 * Environment name the company agent preset's managed-models gate evaluates:
 * a dedicated preset-gate name, deliberately separate from every CLI policy
 * hand-off key (`DESKTOP_POLICY_ENVIRONMENT`). The hand-off carries the RAW
 * `managedModels` flag as one member of an all-five group that
 * `desktopPolicyFromEnvironment` refuses to decode partially, while this
 * gate encodes the EFFECTIVE posture below — one shared name would blur two
 * facts and leave a lone hand-off-shaped key sitting in the shared host
 * environment, poison for any future consumer reading the hand-off from a
 * host snapshot. The `DSH_` prefix keeps this launcher-owned name under the
 * same protections as the other `DSH_*` names: scrubbed out of login-shell
 * captures and rejected by `.env` layers.
 */
export const PRESET_MANAGED_MODELS_GATE = 'DSH_COMPANY_MANAGED_MODELS'

/**
 * The process-environment entry the company agent preset's managed-models
 * gate reads. The Deloitte preset's `tool-web` row carries a `!!js` disabled
 * expression over {@link PRESET_MANAGED_MODELS_GATE} exactly (web search
 * rides api.deepseek.com with `DEEPSEEK_API_KEY`, a credential managed users
 * do not hold), and Loader expressions evaluate in the Host process — so the
 * launcher must write the value into `process.env` before the Host
 * composition loads the preset.
 *
 * The value pins the EFFECTIVE managed posture — `locked` && `managedModels`
 * — and every other build resolves to `'0'`: the launcher writes the entry
 * unconditionally, so an open, unlocked, or development build both evaluates
 * the gate to false and scrubs any stray inherited `'1'`, restoring the
 * native enabled tool exactly as upstream ships it.
 * @param policy - embedded desktop policy of this launch.
 * @returns the environment name and value to write before Host composition.
 */
export function managedModelsPresetGateEntry(
  policy: DesktopPolicy,
): Readonly<{ readonly name: string, readonly value: string }> {
  return {
    name: PRESET_MANAGED_MODELS_GATE,
    value: policy.locked && policy.managedModels ? '1' : '0',
  }
}

/** The `llm-pi-ai` provider profile a managed build registers in memory. */
export interface CompanyModelGatewayProviderProfile {
  /** Selector label. */
  readonly displayName: string
  /** Credential reference resolved per request through the credentials seam. */
  readonly apiKeyEnv: string
  /** OpenAI-compatible wire protocol (the gateway is chat-completions shaped). */
  readonly api: 'openai-completions'
  /** Gateway endpoint. */
  readonly baseURL: string
  /** Served models; unspecified capabilities fall back to the route defaults the adapter owns. */
  readonly models: readonly CompanyModelGatewayModel[]
}

/**
 * Render the composition-layer `llm-pi-ai` provider profile for one managed
 * gateway provider. The gateway's `/models` endpoint is absent (404), so the
 * model list is exactly the blob's list — no dynamic discovery is attempted.
 * Each model entry passes through its optional display name, capacities,
 * and input modalities (upstream `catalog.ts` consumes exactly `name`,
 * `contextWindow`, `maxTokens`, and `input` off a profile model, falling
 * back to the route defaults for whatever is absent). The response is a reasoning-model format regardless
 * of request configuration, so the profile declares no reasoning-effort
 * levels: the harness surfaces the returned reasoning content without
 * asking the gateway to think.
 * @param provider - one decoded provider from the company gateway blob.
 * @returns the provider profile pinned into the composition base layer.
 */
export function companyModelGatewayProviderProfile(
  provider: CompanyModelGatewayProvider,
): CompanyModelGatewayProviderProfile {
  return {
    displayName: provider.displayName,
    apiKeyEnv: provider.apiKeyEnv,
    api: 'openai-completions',
    baseURL: provider.baseUrl,
    models: provider.models.map(({ id, name, contextWindow, maxTokens, input }) => ({
      id,
      ...(name === undefined ? {} : { name }),
      ...(contextWindow === undefined ? {} : { contextWindow }),
      ...(maxTokens === undefined ? {} : { maxTokens }),
      ...(input === undefined ? {} : { input: [...input] }),
    })),
  }
}

/**
 * The default model selection a managed build pins: the first provider's
 * first listed model (the generator writes the pinned default first).
 * @param gateway - decoded company gateway facts.
 * @returns the `agent-default-model` row config values.
 */
export function companyModelGatewayDefaultModel(
  gateway: CompanyModelGateway,
): { readonly provider: string, readonly model: string } {
  const provider = gateway.providers[0]
  if (provider === undefined) throw invalidBlob('the provider list is empty')
  const model = provider.models[0]
  if (model === undefined) throw invalidBlob(`provider "${provider.route}" carries no models`)
  return { provider: provider.route, model: model.id }
}

/** Result of the read-only probe over the managed credentials document. */
export type StoredCredentialNames =
  | { readonly status: 'ok'; readonly names: ReadonlySet<string> }
  | { readonly status: 'unreadable'; readonly reason: string }

/**
 * Read-only probe of the credentials document the upstream
 * `dsh-credentials-local` provider owns, parsed with that package's own
 * strict parser so the yield decision uses the store's real semantics
 * instead of an invented reader. Nothing is written; values are never read
 * out — membership in `refs` is the whole question.
 * @param credentialsPath - absolute path of `.credentials.yaml`.
 * @returns the stored reference names, or why the store could not be read.
 */
export function readStoredCredentialNames(credentialsPath: string): StoredCredentialNames {
  let text: string
  try {
    text = readFileSync(credentialsPath, 'utf8')
  } catch (cause) {
    const code = (cause as NodeJS.ErrnoException | null)?.code
    if (code === 'ENOENT') return { status: 'ok', names: new Set() }
    return {
      status: 'unreadable',
      reason: `the credentials document at ${credentialsPath} is unreadable: ${code ?? (cause instanceof Error ? cause.message : String(cause))}`,
    }
  }
  try {
    return { status: 'ok', names: new Set(parseCredentialsDocument(text, credentialsPath).refs.keys()) }
  } catch (cause) {
    return {
      status: 'unreadable',
      reason: cause instanceof Error ? cause.message : String(cause),
    }
  }
}

/** Inputs of the managed-mode environment injection decision. */
export interface ManagedModelGatewayEnvironmentProbe {
  /**
   * The inherited process environment. Each provider's {@link
   * CompanyModelGatewayProvider.apiKeyEnv} is looked up here; an empty string
   * counts as unset, mirroring how the upstream credentials seam treats the
   * environment layer.
   */
  readonly inheritedEnvironment: Readonly<Record<string, string | undefined>>
  /** Read-only probe of the managed credentials document. */
  readonly storedCredentials: StoredCredentialNames
}

/** Why one provider's launcher credential was — or was not — injected. */
export type ManagedModelGatewayProviderEnvironmentReason =
  | 'injected'
  | 'user-environment'
  | 'user-credentials'
  | 'unreadable-credential-store'

/** Decision for one provider's credential environment entry. */
export interface ManagedModelGatewayProviderEnvironmentDecision {
  /** The provider the decision belongs to. */
  readonly route: string
  /** The environment name the decision is about. */
  readonly apiKeyEnv: string
  /** Whether the launcher writes its own value for {@link apiKeyEnv}. */
  readonly inject: boolean
  readonly reason: ManagedModelGatewayProviderEnvironmentReason
}

/** Decision of {@link resolveManagedModelGatewayEnvironment}. */
export type ManagedModelGatewayEnvironmentDecision =
  | { readonly managed: false, readonly reason: 'unmanaged-build' }
  | {
    readonly managed: true
    /** The exact environment entries to write: one per provider that passed the yield checks. */
    readonly environment: Readonly<Record<string, string>>
    /** Per-provider outcomes, blob order. */
    readonly providers: readonly ManagedModelGatewayProviderEnvironmentDecision[]
  }

/**
 * Decide which gateway credentials this launch injects into the process
 * environment — one decision per provider, each honoring the same
 * user-priority yield semantics the single-provider era defined:
 *
 * - the inherited environment already carries the provider's variable (the
 *   layer `credentials-local` trusts most and treats as read-only), or
 * - the user already stored that reference in `.credentials.yaml`
 *   (the layer the Models page writes),
 *
 * then the user's own configuration wins and this launcher injects nothing
 * for that provider — independently of every other provider. A `.env` file
 * cannot carry these names (upstream rejects `DSH_*` names there), so no
 * third case exists. An unreadable credentials store yields for every
 * provider: the upstream provider will surface that failure on its own load
 * path, and a half-informed injection could not be trusted to lose to a
 * layer it could not read.
 * @param gateway - decoded company gateway facts; undefined for unmanaged builds.
 * @param probe - yield-decision inputs.
 * @returns the per-provider injection decisions plus the exact environment
 * entries to write.
 */
export function resolveManagedModelGatewayEnvironment(
  gateway: CompanyModelGateway | undefined,
  probe: ManagedModelGatewayEnvironmentProbe,
): ManagedModelGatewayEnvironmentDecision {
  if (gateway === undefined) return { managed: false, reason: 'unmanaged-build' }
  const unreadable = probe.storedCredentials.status === 'unreadable'
  const storedNames = unreadable ? undefined : probe.storedCredentials.names
  const decisions = gateway.providers.map((provider): ManagedModelGatewayProviderEnvironmentDecision => {
    const inherited = probe.inheritedEnvironment[provider.apiKeyEnv]
    if ((inherited ?? '').length > 0) {
      return { route: provider.route, apiKeyEnv: provider.apiKeyEnv, inject: false, reason: 'user-environment' }
    }
    if (unreadable) {
      return { route: provider.route, apiKeyEnv: provider.apiKeyEnv, inject: false, reason: 'unreadable-credential-store' }
    }
    if (storedNames?.has(provider.apiKeyEnv) === true) {
      return { route: provider.route, apiKeyEnv: provider.apiKeyEnv, inject: false, reason: 'user-credentials' }
    }
    return { route: provider.route, apiKeyEnv: provider.apiKeyEnv, inject: true, reason: 'injected' }
  })
  const environment: Record<string, string> = {}
  for (const [index, decision] of decisions.entries()) {
    if (decision.inject) environment[decision.apiKeyEnv] = gateway.providers[index]!.apiKey
  }
  return { managed: true, environment, providers: decisions }
}

/**
 * Resolve the credentials document path the same way the upstream provider
 * does, so the probe and the provider can never disagree about the file.
 * @param home - Harness home directory.
 * @returns the absolute `.credentials.yaml` path.
 */
export function storedCredentialsPath(home: string): string {
  return resolveSpec({ dshHome: home }).filename
}

// ---------------------------------------------------------------------------
// Guardrail per-turn injection (#046).
//
// Managed builds prepend a fixed security-policy template (the guardrail
// security prompt, see `company-guardrail.ts` for the three resolution
// layers) to the LAST `role: 'user'` message of every chat-completions
// request the company gateway serves. The rewrite is a tripwire, not a
// gate: it hardens against hand-slips, and it never touches non-locked or
// development traffic — the fetch boundary below installs only on the
// managed path (`managedModelGateway` decoded a locked, managedModels
// policy), and every other fetch the process makes rides the wrapper
// untouched (exact chat-completions URL match, nothing else).
//
// The seam is the process fetch boundary: the upstream `llm-pi-ai` adapter
// builds provider requests through pi-ai's openai-completions client,
// which resolves its fetch per request from `globalThis.fetch` in the Host
// process — the process this launcher owns. Neither the pinned submodule
// nor any upstream adapter is modified; the wrapper is installed before the
// Host composition boots and rewrites the JSON body of exactly the managed
// gateway chat-completions POSTs.
//
// Prefix-cache safety: ONLY the last user message is rewritten. Every
// message before it stays the same object reference in the rebuilt body —
// byte-identical on the wire — so the provider's prefix cache keeps
// matching the conversation prefix turn over turn.
// ---------------------------------------------------------------------------

/** Separator between the frozen template text and the original user input. */
const GUARDRAIL_ASSEMBLY_SEPARATOR = '\n\n'

/**
 * The user-input placeholder token the template carries: the token's whole
 * purpose is to be REPLACED by the user's original input at assembly time,
 * so the input lands inside the template's `<USER>` wrapper block — never
 * appended after the template with the literal token still riding along
 * (July's design; the append-only assembly was a review-fixed mistake).
 */
const GUARDRAIL_PLACEHOLDER_TOKEN = '{user_input_placeholder}'

/**
 * The idempotence marker: the template's bytes up to (not including) the
 * placeholder token — everything a rewritten message is guaranteed to start
 * with once the template has been applied, regardless of what the user's
 * input turned out to be. A template without the token falls back to the
 * whole template as its own marker.
 */
function companyGatewayGuardrailMarker(template: string): string {
  const at = template.indexOf(GUARDRAIL_PLACEHOLDER_TOKEN)
  return at === -1 ? template : template.slice(0, at)
}

/**
 * The per-turn assembly shape: FILL, not append. The template's
 * `{user_input_placeholder}` token is replaced by the user's original
 * input — with the frozen v1 shape the model sees `<GUARDRAIL …policy…
 * </GUARDRAIL>… <USER>\n<original input>\n</USER>`: the policy precedes the
 * input and the input sits inside the wrapper block. A template carrying
 * no token keeps the legacy append shape (`<template>\n\n<original>`).
 * @param template - the active guardrail template text.
 * @param original - the user message's original content.
 * @returns the assembled content.
 */
export function companyGatewayGuardrailAssembly(template: string, original: string): string {
  const at = template.indexOf(GUARDRAIL_PLACEHOLDER_TOKEN)
  if (at === -1) return `${template}${GUARDRAIL_ASSEMBLY_SEPARATOR}${original}`
  return `${template.slice(0, at)}${original}${template.slice(at + GUARDRAIL_PLACEHOLDER_TOKEN.length)}`
}

/** A multipart content part of a chat-completions message. */
interface ChatCompletionsContentPart {
  readonly type: unknown
  readonly text?: unknown
  [field: string]: unknown
}

/** Result of {@link applyCompanyGatewayGuardrail}. */
export interface CompanyGatewayGuardrailRewrite {
  /** Whether the rewrite changed the body (a template was prepended). */
  readonly changed: boolean
  /** The rewritten body; the input reference itself when unchanged. */
  readonly body: unknown
}

/**
 * Rewrite one PARSED chat-completions request body: find the LAST message
 * with `role === 'user'` and apply the active template to its content —
 * FILL semantics for a token-carrying template: the string content becomes
 * the template with its `{user_input_placeholder}` token REPLACED by the
 * original input (input inside the `<USER>` wrapper); a token-less
 * template keeps the legacy append shape (`<template>\n\n<original>`);
 * a multipart content gains one leading `text` part carrying the template
 * with the token stripped. The rewrite is idempotent per request body: a
 * content that already starts with the template's prefix-before-token (or
 * the whole template when it carries no token — the same body passing the
 * boundary twice, an adapter-internal retry of the rewritten body) is
 * returned unchanged, so the template applies at most once per request
 * body. Harness-level
 * retries re-send the ORIGINAL body (the session history never sees the
 * wire rewrite), which the same guard then covers exactly once again.
 *
 * Every other message keeps its object reference inside the rebuilt
 * messages array — the prior context stays byte-identical, which is what
 * the provider prefix cache matches. A body without a user message, a last
 * user message whose content shape carries no text, an empty template, or
 * any non-object body returns unchanged: a tripwire must never break the
 * request it rides on.
 * @param body - the parsed chat-completions request body.
 * @param template - the active guardrail template text.
 * @returns the rewrite decision and body.
 */
export function applyCompanyGatewayGuardrail(body: unknown, template: string): CompanyGatewayGuardrailRewrite {
  if (typeof template !== 'string' || template.length === 0) return { changed: false, body }
  if (body === null || typeof body !== 'object' || Array.isArray(body)) return { changed: false, body }
  const request = body as Record<string, unknown>
  if (!Array.isArray(request.messages)) return { changed: false, body }
  const messages = request.messages as readonly unknown[]
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const message = messages[index]
    if (message === null || typeof message !== 'object' || Array.isArray(message)) continue
    const record = message as Record<string, unknown>
    if (record.role !== 'user') continue
    // The LAST user message is the one and only injection point; a content
    // shape that carries no text at all leaves the whole body unchanged
    // rather than walking back to an earlier user message.
    const content = record.content
    if (typeof content === 'string') {
      if (content.startsWith(companyGatewayGuardrailMarker(template))) return { changed: false, body }
      const rewritten: unknown[] = [...messages]
      rewritten[index] = { ...record, content: companyGatewayGuardrailAssembly(template, content) }
      return { changed: true, body: { ...request, messages: rewritten } }
    }
    if (Array.isArray(content)) {
      const parts = content as readonly ChatCompletionsContentPart[]
      const marker = companyGatewayGuardrailMarker(template)
      const first = parts[0]
      if (first !== undefined && first !== null && typeof first === 'object' && !Array.isArray(first)
        && first.type === 'text' && typeof first.text === 'string' && first.text.startsWith(marker)) {
        return { changed: false, body }
      }
      // A multipart user message (tool-result continuations, text beside
      // images) has no single string to fill the placeholder with: the
      // policy text rides as a leading text part with the placeholder token
      // emptied, and the original parts follow untouched in the same user
      // message the wrapper block conceptually covers.
      const rewritten: unknown[] = [...messages]
      const rewrittenContent: ChatCompletionsContentPart[] = [
        { type: 'text', text: `${template.split(GUARDRAIL_PLACEHOLDER_TOKEN).join('')}${GUARDRAIL_ASSEMBLY_SEPARATOR}` },
        ...parts,
      ]
      rewritten[index] = { ...record, content: rewrittenContent }
      return { changed: true, body: { ...request, messages: rewritten } }
    }
    return { changed: false, body }
  }
  return { changed: false, body }
}

/** Fetch boundary shape the guardrail wrapper wraps (`globalThis.fetch`). */
export type CompanyGatewayFetchBoundary = typeof globalThis.fetch

/**
 * The exact chat-completions endpoint URLs of every managed provider: the
 * provider's blob base URL with any trailing slash normalized away plus
 * `/chat/completions` — the wire path pi-ai's openai-completions client
 * posts model requests to. Matching is exact-set membership, the cheapest
 * possible gate in front of every other fetch the process makes.
 * @param gateway - decoded company gateway facts.
 * @returns the chat-completions URL set.
 */
export function companyGatewayChatCompletionsUrls(gateway: CompanyModelGateway): ReadonlySet<string> {
  // Built through `new URL(...).href` so the set entry carries exactly the
  // normalizations the request URL will carry at request time (host
  // lowercasing, explicit-`:443` stripping, punycode): a raw
  // `baseUrl + '/chat/completions'` string would silently MISS those
  // providers' requests and the tripwire would go inert with no error
  // (review #046 P3).
  const urls = new Set<string>()
  for (const provider of gateway.providers) {
    const base = new URL(provider.baseUrl)
    urls.add(new URL('chat/completions', `${base.href.replace(/\/+$/u, '')}/`).href)
  }
  return urls
}

/**
 * Wrap one fetch boundary with the guardrail rewrite: POSTs whose URL is
 * exactly one of the managed gateway chat-completions endpoints and whose
 * body is a JSON string get the active template prepended to their last
 * user message; EVERYTHING else — other URLs, other methods, already-
 * rewritten bodies, non-string bodies, unparseable JSON — rides the inner
 * boundary byte for byte. Any parse or serialization failure forwards the
 * original bytes: the tripwire never breaks the request it rides on. The
 * active template is read per request through `template()`, so a
 * boot-time resolution that lands after installation goes live on the
 * next request without reinstalling.
 * @param inner - the fetch boundary being wrapped.
 * @param chatCompletionsUrls - the exact URLs to rewrite (see {@link companyGatewayChatCompletionsUrls}).
 * @param template - accessor for the currently active template text.
 * @returns the wrapping fetch boundary.
 */
export function companyGatewayGuardrailFetchBoundary(
  inner: CompanyGatewayFetchBoundary,
  chatCompletionsUrls: ReadonlySet<string>,
  template: () => string,
): CompanyGatewayFetchBoundary {
  return (url, init) => {
    const active = template()
    if (active.length > 0 && typeof url === 'string' && chatCompletionsUrls.has(url)
      && init !== null && typeof init === 'object' && init.method === 'POST' && typeof init.body === 'string') {
      try {
        const rewrite = applyCompanyGatewayGuardrail(JSON.parse(init.body) as unknown, active)
        if (rewrite.changed) {
          return inner(url, { ...init, body: JSON.stringify(rewrite.body) })
        }
      } catch {
        // A body the rewrite cannot parse or re-serialize forwards untouched.
      }
    }
    return inner(url, init)
  }
}

/** Marker symbol identifying an installed guardrail fetch wrapper. */
const INSTALLED_COMPANY_GATEWAY_GUARDRAIL_FETCH = Symbol('dsh-company-gateway-guardrail-fetch')

/**
 * Install the guardrail fetch wrapper on one target (the Electron main
 * process's `globalThis`, whose Host composes the `llm-pi-ai` adapter).
 * Managed path only: an `undefined` gateway (every non-locked, dev, or
 * non-managed build) installs nothing and returns false, keeping the
 * process fetch boundary exactly as upstream ships it. Installation is
 * idempotent — a second call finds the marker and never stacks wrappers.
 * @param target - the object whose `fetch` is replaced (globalThis).
 * @param gateway - decoded company gateway facts; undefined stays inert.
 * @param template - accessor for the currently active template text.
 * @returns whether a wrapper is installed after the call.
 */
export function installCompanyGatewayGuardrailFetch(
  target: { fetch: CompanyGatewayFetchBoundary },
  gateway: CompanyModelGateway | undefined,
  template: () => string,
): boolean {
  if (gateway === undefined) return false
  const existing = target.fetch as CompanyGatewayFetchBoundary & { [INSTALLED_COMPANY_GATEWAY_GUARDRAIL_FETCH]?: boolean }
  if (existing[INSTALLED_COMPANY_GATEWAY_GUARDRAIL_FETCH] === true) return true
  const wrapper = companyGatewayGuardrailFetchBoundary(target.fetch, companyGatewayChatCompletionsUrls(gateway), template)
  ;(wrapper as CompanyGatewayFetchBoundary & { [INSTALLED_COMPANY_GATEWAY_GUARDRAIL_FETCH]?: boolean })[INSTALLED_COMPANY_GATEWAY_GUARDRAIL_FETCH] = true
  target.fetch = wrapper
  return true
}
