/**
 * Per-call model usage reporting to the company telemetry database (P5).
 *
 * PRIVACY CONTRACT (design review, 2026-09-01): one row per assistant step
 * carries ONLY token counts, provider/model attribution, and wall-clock
 * timing. No prompt, response, reasoning, tool, or error text is ever read
 * from the message, and the log surface of this module is counters and
 * connection status only. `session_id` is an indirect identifier (it reveals
 * when and how much was sent, never what) and stays in the company database.
 *
 * Composition facts:
 *
 * - The plugin subscribes to `session/event` for `request/header` (the
 *   per-session call-config attribution the assembled message does not
 *   carry), `step/start`/`assistant/chunk` (timing boundaries), and
 *   `assistant/message` (the usage record). Upstream guarantees exactly one
 *   assembled message per step; the `(session_id, turn, step)` in-memory
 *   dedup is defensive only, mirrored by the table's UNIQUE key and
 *   INSERT-only writer.
 * - `total_tokens` is the four disjoint buckets (input + cache read + cache
 *   write + output) exactly like the upstream token meter;
 *   `reasoningTokens` is a SUBSET of `outputTokens` and never enters the
 *   total.
 * - Timing mirrors `sessionStats` projection math: latency is
 *   `step/start → assistant/message`, TTFT is the first non-empty delta
 *   chunk, and tokens/second is output tokens over the decode span. A
 *   boundary whose (turn, step) does not match the assembled message is
 *   rejected exactly like `sessionStats` rejects it — the row survives with
 *   NULL timing instead of inheriting a stale step's clock.
 * - Queueing is bounded (5 000 rows, drop-oldest plus a counter) and flushed
 *   on a double trigger (50 rows or every 10 s). The MySQL connection is
 *   created lazily on the FIRST flush attempt — the module never touches
 *   the network from the startup path, and a disabled policy keeps it fully
 *   unwired (no subscription, no connection, no blob decode).
 * - Credentials: a low-privilege INSERT-only account, shipped as an
 *   XOR+base64 obfuscated blob (`src/usage-report-db-blob.ts`, generated by
 *   `scripts/make-usage-report-blob.mjs`; obfuscation is not encryption).
 *   `DSH_REPORT_DB_*` environment overrides are honored in unpackaged runs
 *   only, exactly like the `DSH_SSO_*` pattern. The DSN never enters any
 *   log line: errors pass through {@link sanitizeUsageReportError} before
 *   the logger sees them.
 *
 * @module dsh-plugin-desktop/model-usage-report
 */

import { readFileSync } from 'node:fs'
import type { Context } from '@deepseek-ai/cordis'
import type { TokenUsage } from '@deepseek-ai/dsh-llm'
import { isTokenDelta } from '@deepseek-ai/dsh-llm/message'
import type { Session, SessionEvent } from '@deepseek-ai/dsh-session'
import { readDesktopPolicy, type DesktopPolicy } from './desktop-policy.ts'
import { maskSecrets } from './mask-secrets.ts'
import {
  COMPANY_LLM_GATEWAY_PROVIDER_ROUTE,
  managedModelGateway,
} from './model-gateway.ts'
import { MODEL_GATEWAY_BLOB } from './model-gateway-blob.ts'
import { isPackagedApplicationPath } from './packaged-runtime-path.ts'
import { USAGE_REPORT_DB_BLOB } from './usage-report-db-blob.ts'

/** Stable Cordis plugin name (cordis.patch.yml row `desktop-model-usage-report`). */
export const name = 'desktop-model-usage-reporter'

/** The runtime service probe; `sessions` attaches independently below. */
export const inject = ['desktopRuntime']

// ---------------------------------------------------------------------------
// Queue shape constants (exported for tests and operations documentation)
// ---------------------------------------------------------------------------

/** Hard in-memory queue ceiling; the oldest rows are dropped beyond it. */
export const MODEL_USAGE_QUEUE_LIMIT_ROWS = 5_000
/** Row count that triggers a flush on its own. */
export const MODEL_USAGE_FLUSH_THRESHOLD_ROWS = 50
/** Maximum time a queued row waits for the interval trigger. */
export const MODEL_USAGE_FLUSH_INTERVAL_MS = 10_000
/** mysql2 connection handshake deadline. */
export const MODEL_USAGE_CONNECT_TIMEOUT_MS = 8_000
/** First reconnect delay after a failed write; doubles from here. */
export const MODEL_USAGE_RECONNECT_BASE_MS = 1_000
/** Reconnect backoff ceiling. */
export const MODEL_USAGE_RECONNECT_MAX_MS = 60_000

// ---------------------------------------------------------------------------
// Database destination
// ---------------------------------------------------------------------------

/** Target table (company MySQL, database `dsh_usage`). */
export const MODEL_USAGE_TABLE = 'dsh_model_call_events'

/** Column order of the INSERT statement; values follow the same order. */
export const MODEL_USAGE_COLUMNS: readonly string[] = Object.freeze([
  'user_email',
  'provider',
  'model',
  'base_url',
  'input_tokens',
  'cache_read_tokens',
  'cache_write_tokens',
  'output_tokens',
  'reasoning_tokens',
  'total_tokens',
  'tokens_per_second',
  'ttft_ms',
  'latency_ms',
  'session_id',
  'turn',
  'step',
  'client_version',
  'created_at',
])

/** Decoded report-database destination; the password never enters a log. */
export interface UsageReportDbDsn {
  readonly host: string
  readonly port: number
  readonly user: string
  readonly password: string
  readonly database: string
}

/**
 * Fixed XOR key. NOT a secret: it must stay byte-identical to
 * `scripts/make-usage-report-blob.mjs` or the decode fails loudly.
 */
const OBFUSCATION_KEY = 'dsh-desktop-usage-report-obfuscation-key-v1'

function invalidDsn(message: string): Error {
  return new Error(`dsh-plugin-desktop: invalid usage report database blob: ${message}`)
}

const HOST_PATTERN = /^[A-Za-z0-9._-]{1,253}$/u

/** Strictly validate one decoded DSN document (shared by blob and env paths). */
function parseDsnDocument(document: unknown): UsageReportDbDsn {
  if (typeof document !== 'object' || document === null || Array.isArray(document)) {
    throw invalidDsn('the decoded payload must be an object')
  }
  const keys = Object.keys(document).sort()
  if (keys.length !== 5 || keys[0] !== 'database' || keys[1] !== 'host' || keys[2] !== 'password'
    || keys[3] !== 'port' || keys[4] !== 'user') {
    throw invalidDsn('the decoded payload must carry exactly host, port, user, password, and database')
  }
  const { host, port, user, password, database } = document as Record<string, unknown>
  if (typeof host !== 'string' || !HOST_PATTERN.test(host)) {
    throw invalidDsn('host must be a bare hostname or IP literal')
  }
  if (typeof port !== 'number' || !Number.isInteger(port) || port < 1 || port > 65_535) {
    throw invalidDsn('port must be an integer between 1 and 65535')
  }
  if (typeof user !== 'string' || user.length === 0) {
    throw invalidDsn('user must be a non-empty string')
  }
  if (typeof password !== 'string' || password.length === 0) {
    throw invalidDsn('password must be a non-empty string')
  }
  if (typeof database !== 'string' || database.length === 0) {
    throw invalidDsn('database must be a non-empty string')
  }
  return Object.freeze({ host, port, user, password, database })
}

/**
 * Decode and strictly validate one obfuscated report-database blob.
 * @param blob - base64 XOR-obfuscated JSON DSN.
 * @returns the validated destination facts.
 * @throws when the blob is malformed; the message never includes blob content.
 */
export function decodeUsageReportDbBlob(blob: string): UsageReportDbDsn {
  if (typeof blob !== 'string' || blob.length === 0) {
    throw invalidDsn('the blob must be a non-empty string')
  }
  let cipher: Buffer
  try {
    cipher = Buffer.from(blob, 'base64')
  } catch (cause) {
    throw invalidDsn(`base64 decoding failed: ${cause instanceof Error ? cause.message : String(cause)}`)
  }
  const key = Buffer.from(OBFUSCATION_KEY, 'utf8')
  const plain = Buffer.from(cipher)
  for (let index = 0; index < plain.length; index += 1) {
    plain[index] = plain[index]! ^ key[index % key.length]!
  }
  let document: unknown
  try {
    document = JSON.parse(plain.toString('utf8')) as unknown
  } catch {
    throw invalidDsn('the decoded payload is not valid JSON')
  }
  return parseDsnDocument(document)
}

/** Environment names of the unpackaged-only destination overrides. */
export const USAGE_REPORT_DB_ENVIRONMENT = Object.freeze({
  host: 'DSH_REPORT_DB_HOST',
  port: 'DSH_REPORT_DB_PORT',
  user: 'DSH_REPORT_DB_USER',
  password: 'DSH_REPORT_DB_PASSWORD',
  database: 'DSH_REPORT_DB_DATABASE',
})

function environmentValue(environment: NodeJS.ProcessEnv, name: string): string | undefined {
  const value = environment[name]
  if (value === undefined) return undefined
  const trimmed = value.trim()
  return trimmed.length === 0 ? undefined : trimmed
}

/**
 * Resolve the report destination: the embedded blob, plus `DSH_REPORT_DB_*`
 * field overrides honored in unpackaged runs only (the `DSH_SSO_*` pattern —
 * a packaged build always uses the pinned blob).
 * @param blob - obfuscated DSN blob (override for tests).
 * @param environment - environment carrying optional overrides.
 * @param moduleUrl - module URL deciding the packaged-layout check.
 * @returns the validated destination.
 * @throws when the blob or the overridden combination is invalid.
 */
export function resolveUsageReportDbDsn(
  blob: string = USAGE_REPORT_DB_BLOB,
  environment: NodeJS.ProcessEnv = process.env,
  moduleUrl: string = import.meta.url,
): UsageReportDbDsn {
  const dsn = decodeUsageReportDbBlob(blob)
  if (isPackagedApplicationPath(fileUrlToPathSafe(moduleUrl))) return dsn
  const host = environmentValue(environment, USAGE_REPORT_DB_ENVIRONMENT.host)
  const port = environmentValue(environment, USAGE_REPORT_DB_ENVIRONMENT.port)
  const user = environmentValue(environment, USAGE_REPORT_DB_ENVIRONMENT.user)
  const password = environmentValue(environment, USAGE_REPORT_DB_ENVIRONMENT.password)
  const database = environmentValue(environment, USAGE_REPORT_DB_ENVIRONMENT.database)
  if (host === undefined && port === undefined && user === undefined
    && password === undefined && database === undefined) return dsn
  const portNumber = port === undefined ? dsn.port : Number.parseFloat(port)
  return parseDsnDocument({
    host: host ?? dsn.host,
    port: portNumber,
    user: user ?? dsn.user,
    password: password ?? dsn.password,
    database: database ?? dsn.database,
  })
}

function fileUrlToPathSafe(moduleUrl: string): string {
  try {
    // Imported lazily-shaped to keep this module free of a node:url side effect
    // at parse time for bundlers that inline it; the URL case is the only one.
    return new URL(moduleUrl).pathname
  } catch {
    return moduleUrl
  }
}

// ---------------------------------------------------------------------------
// Row projection (pure fold over session events)
// ---------------------------------------------------------------------------

/** One telemetry row: token counts, attribution, timing, and identity only. */
export interface ModelUsageRow {
  readonly userEmail: string
  readonly provider: string
  readonly model: string
  readonly baseUrl: string
  readonly inputTokens: number
  readonly cacheReadTokens: number | null
  readonly cacheWriteTokens: number | null
  readonly outputTokens: number
  readonly reasoningTokens: number | null
  readonly totalTokens: number
  readonly tokensPerSecond: number | null
  readonly ttftMs: number | null
  readonly latencyMs: number | null
  readonly sessionId: string | null
  readonly turn: number
  readonly step: number
  readonly clientVersion: string
  readonly createdAt: Date
}

/** Per-row inputs the session log cannot supply. */
export interface ModelUsageAttribution {
  /** Authenticated SSO account email, or '' — reporting never depends on SSO. */
  readonly userEmail: () => string
  /**
   * Base URL attribution for one provider route. The managed company gateway
   * resolves to the gateway blob's base URL; every other provider route has
   * no desktop-side source of truth (user-configured endpoints live in the
   * credentials seam, which this collector must not read), so it resolves to
   * ''.
   */
  readonly baseUrlFor: (provider: string) => string
  /** Desktop product version stamped on every row. */
  readonly clientVersion: string
}

/** Four disjoint buckets, mirroring the upstream token meter's `usageTokens`. */
export function modelUsageTotalTokens(usage: TokenUsage): number {
  return usage.inputTokens
    + (usage.cacheReadTokens ?? 0)
    + (usage.cacheWriteTokens ?? 0)
    + usage.outputTokens
}

function finiteNonNegative(value: unknown): value is number {
  return typeof value === 'number' && Number.isFinite(value) && value >= 0
}

/** A usage record is reportable only when both mandatory counts are valid. */
function reportableUsage(usage: unknown): TokenUsage | undefined {
  if (typeof usage !== 'object' || usage === null) return undefined
  const candidate = usage as Partial<TokenUsage>
  if (!finiteNonNegative(candidate.inputTokens) || !finiteNonNegative(candidate.outputTokens)) {
    return undefined
  }
  return candidate as TokenUsage
}

/** Call-config attribution carried by `request/header` events. */
interface SessionCallConfig {
  readonly provider: string
  readonly model: string
}

/** Timing boundaries of the open step (consumed by its assembled message). */
interface OpenStepBoundaries {
  readonly turn: number
  readonly step: number
  readonly startTime: number
  firstTokenTime: number | null
}

/** Live per-session collection state. */
interface SessionUsageState {
  readonly sessionId: string | null
  config: SessionCallConfig | undefined
  openStep: OpenStepBoundaries | undefined
  /** `${turn}:${step}` keys already enqueued (defensive dedup). */
  readonly reportedSteps: Set<string>
}

/**
 * Pure event-to-row fold. One instance serves the whole firehose; state is
 * keyed per session and released on `session/disposed` so long-running
 * processes do not accumulate dead sessions.
 */
export class ModelUsageProjection {
  readonly #attribution: ModelUsageAttribution
  readonly #sessions = new Map<string, SessionUsageState>()
  readonly #syntheticKeys = new WeakMap<object, string>()
  #nextSyntheticKey = 0

  constructor(attribution: ModelUsageAttribution) {
    this.#attribution = attribution
  }

  /**
   * Fold one firehose event.
   * @param session - the session the event belongs to.
   * @param event - the live session event.
   * @returns the reportable row, or undefined when the event carries none.
   */
  sessionEvent(session: Session, event: SessionEvent): ModelUsageRow | undefined {
    const state = this.#stateFor(session)
    switch (event.type) {
      case 'request/header': {
        const config = event.data.header.config
        if (typeof config.provider === 'string' && config.provider.length > 0
          && typeof config.model === 'string' && config.model.length > 0) {
          state.config = { provider: config.provider, model: config.model }
        }
        return undefined
      }
      case 'step/start':
        state.openStep = {
          turn: event.data.turn,
          step: event.data.step,
          startTime: event.time,
          firstTokenTime: null,
        }
        return undefined
      case 'assistant/chunk': {
        const open = state.openStep
        if (open === undefined || open.turn !== event.data.turn || open.step !== event.data.step) {
          return undefined
        }
        if (open.firstTokenTime === null && isTokenDelta(event.data.chunk)) {
          open.firstTokenTime = event.time
        }
        return undefined
      }
      case 'assistant/message': {
        const open = state.openStep
        // Only a boundary whose (turn, step) matches this message may source
        // timing. A stale step must not lend its clock to a different row:
        // the session-stats projection rejects such messages outright; here
        // the tokens still count, but the three timing columns go NULL
        // instead of being misattributed to the leftover step.
        const boundary = open !== undefined && open.turn === event.data.turn && open.step === event.data.step
          ? open
          : undefined
        // Consume the boundary regardless of reportability so a defensive
        // duplicate message cannot accrue stale timing.
        if (boundary !== undefined) {
          state.openStep = undefined
        }
        const usage = reportableUsage(event.data.usage)
        if (usage === undefined) return undefined
        const stepKey = `${String(event.data.turn)}:${String(event.data.step)}`
        if (state.reportedSteps.has(stepKey)) return undefined
        state.reportedSteps.add(stepKey)
        const provider = state.config?.provider ?? ''
        return {
          userEmail: this.#attribution.userEmail(),
          provider,
          model: state.config?.model ?? '',
          baseUrl: this.#attribution.baseUrlFor(provider),
          inputTokens: usage.inputTokens,
          cacheReadTokens: finiteNonNegative(usage.cacheReadTokens) ? usage.cacheReadTokens : null,
          cacheWriteTokens: finiteNonNegative(usage.cacheWriteTokens) ? usage.cacheWriteTokens : null,
          outputTokens: usage.outputTokens,
          reasoningTokens: finiteNonNegative(usage.reasoningTokens) ? usage.reasoningTokens : null,
          // reasoning is a subset of output and deliberately NOT added here.
          totalTokens: modelUsageTotalTokens(usage),
          tokensPerSecond: decodeTokensPerSecond(boundary, event, usage),
          ttftMs: boundary !== undefined && boundary.firstTokenTime !== null
            ? Math.max(0, boundary.firstTokenTime - boundary.startTime)
            : null,
          latencyMs: boundary === undefined ? null : Math.max(0, event.time - boundary.startTime),
          sessionId: state.sessionId,
          turn: event.data.turn,
          step: event.data.step,
          clientVersion: this.#attribution.clientVersion,
          createdAt: new Date(event.time),
        }
      }
      default:
        return undefined
    }
  }

  /** Release one session's state (config map, boundaries, dedup set). */
  sessionDisposed(session: Session): void {
    const key = this.#keyFor(session)
    if (key === undefined) return
    this.#sessions.delete(key)
  }

  #keyFor(session: Session): string | undefined {
    const id = (session as { header?: { id?: unknown } }).header?.id
    if (typeof id === 'string' && id.length > 0) return id
    const existing = this.#syntheticKeys.get(session)
    if (existing !== undefined) return existing
    this.#nextSyntheticKey += 1
    const synthetic = `#anonymous:${String(this.#nextSyntheticKey)}`
    this.#syntheticKeys.set(session, synthetic)
    return synthetic
  }

  #stateFor(session: Session): SessionUsageState {
    const key = this.#keyFor(session) as string
    let state = this.#sessions.get(key)
    if (state === undefined) {
      const id = (session as { header?: { id?: unknown } }).header?.id
      state = {
        sessionId: typeof id === 'string' && id.length > 0 ? id : null,
        config: undefined,
        openStep: undefined,
        reportedSteps: new Set<string>(),
      }
      this.#sessions.set(key, state)
    }
    return state
  }
}

/** Output tokens over the decode span (first token → assembled message). */
function decodeTokensPerSecond(
  open: OpenStepBoundaries | undefined,
  event: SessionEvent<'assistant/message'>,
  usage: TokenUsage,
): number | null {
  if (open === undefined || open.firstTokenTime === null || usage.outputTokens <= 0) return null
  const decodeMs = Math.max(0, event.time - open.firstTokenTime)
  if (decodeMs === 0) return null
  return (usage.outputTokens * 1_000) / decodeMs
}

// ---------------------------------------------------------------------------
// INSERT statement shape
// ---------------------------------------------------------------------------

/**
 * Render the multi-row INSERT IGNORE statement. Idempotency rests on the
 * table's UNIQUE(session_id, turn, step); NULL session ids never collide
 * (SQL UNIQUE semantics), which is the intended multi-row shape for
 * attribution-less events.
 */
export function modelUsageInsertSql(rowCount: number): string {
  if (!Number.isInteger(rowCount) || rowCount < 1) {
    throw new TypeError('dsh-plugin-desktop: model usage insert needs at least one row')
  }
  const columns = MODEL_USAGE_COLUMNS.map(column => `\`${column}\``).join(', ')
  const placeholders = `(${MODEL_USAGE_COLUMNS.map(() => '?').join(', ')})`
  return `INSERT IGNORE INTO \`${MODEL_USAGE_TABLE}\` (${columns}) VALUES `
    + `${placeholders}${`, ${placeholders}`.repeat(rowCount - 1)}`
}

/** Flatten one row into statement parameters (column order). */
export function modelUsageRowValues(row: ModelUsageRow): unknown[] {
  return [
    row.userEmail,
    row.provider,
    row.model,
    row.baseUrl,
    row.inputTokens,
    row.cacheReadTokens,
    row.cacheWriteTokens,
    row.outputTokens,
    row.reasoningTokens,
    row.totalTokens,
    row.tokensPerSecond,
    row.ttftMs,
    row.latencyMs,
    row.sessionId,
    row.turn,
    row.step,
    row.clientVersion,
    row.createdAt,
  ]
}

// ---------------------------------------------------------------------------
// Write boundary and bounded queue
// ---------------------------------------------------------------------------

/** Connection options the sink hands to the boundary. */
export interface UsageReportConnectionConfig {
  readonly host: string
  readonly port: number
  readonly user: string
  readonly password: string
  readonly database: string
  readonly connectTimeout: number
}

/** One MySQL connection (the mysql2/promise surface the sink uses). */
export interface ModelUsageConnection {
  query(sql: string, values: readonly unknown[]): Promise<unknown>
  end(): Promise<void>
}

/** Injected mysql2 seam; tests substitute a recorder. */
export interface ModelUsageWriteBoundary {
  createConnection(config: UsageReportConnectionConfig): Promise<ModelUsageConnection>
}

/** Boundary factory — resolved lazily so mysql2 never loads eagerly. */
export type ModelUsageWriteBoundaryFactory = () => ModelUsageWriteBoundary | Promise<ModelUsageWriteBoundary>

/**
 * Real mysql2 boundary. Imported lazily from inside the flush path: a
 * disabled or idle reporter never loads the driver, and the dependency stays
 * off the startup path.
 */
export async function createMysql2WriteBoundary(): Promise<ModelUsageWriteBoundary> {
  const mysql = await import('mysql2/promise')
  return {
    async createConnection(config) {
      const connection = await mysql.createConnection({
        host: config.host,
        port: config.port,
        user: config.user,
        password: config.password,
        database: config.database,
        connectTimeout: config.connectTimeout,
      })
      return {
        query: (sql, values) => connection.query(sql, values as unknown[]),
        end: () => connection.end(),
      }
    },
  }
}

/** Injectable timer surface (tests drive flushing deterministically). */
export type ModelUsageSchedule = (delayMs: number, run: () => void) => () => void

/** Counter-only status surface — the whole module's log vocabulary. */
export interface ModelUsageSinkStats {
  readonly queued: number
  readonly flushed: number
  readonly dropped: number
  readonly errors: number
  readonly connected: boolean
}

/** Sink construction options; every dependency is injectable. */
export interface ModelUsageSinkOptions {
  readonly now?: (() => number) | undefined
  readonly schedule?: ModelUsageSchedule | undefined
  readonly logInfo?: ((message: string) => void) | undefined
  readonly logError?: ((message: string) => void) | undefined
}

/**
 * Bounded in-memory queue with a lazy MySQL connection.
 *
 * Flush triggers: the row threshold on enqueue, the interval timer armed
 * while rows wait, and a final best-effort drain on {@link ModelUsageSink.dispose}
 * (Cordis unload awaits the async disposer, so application shutdown drains
 * within the launcher's shutdown grace). Failed writes keep their rows
 * queued and reconnect with a doubling backoff capped at
 * {@link MODEL_USAGE_RECONNECT_MAX_MS}.
 */
export class ModelUsageSink {
  readonly #createBoundary: ModelUsageWriteBoundaryFactory
  readonly #dsn: UsageReportDbDsn
  readonly #now: () => number
  readonly #schedule: ModelUsageSchedule
  readonly #logInfo: (message: string) => void
  readonly #logError: (message: string) => void

  readonly #queue: ModelUsageRow[] = []
  #flushed = 0
  #dropped = 0
  #errors = 0
  #lastFlushAt: number
  #flushing: Promise<void> | undefined
  #flushAgain = false
  #intervalTimer: (() => void) | undefined
  #retryTimer: (() => void) | undefined
  #retryNotBefore = 0
  #backoffMs = 0
  #connection: ModelUsageConnection | undefined
  #connectionTask: Promise<ModelUsageConnection> | undefined
  #disposed = false
  #disposing = false

  constructor(
    createBoundary: ModelUsageWriteBoundaryFactory,
    dsn: UsageReportDbDsn,
    options: ModelUsageSinkOptions = {},
  ) {
    this.#createBoundary = createBoundary
    this.#dsn = dsn
    this.#now = options.now ?? (() => Date.now())
    this.#schedule = options.schedule ?? ((delayMs, run) => {
      const handle = setTimeout(run, delayMs)
      return () => { clearTimeout(handle) }
    })
    this.#logInfo = options.logInfo ?? (() => {})
    this.#logError = options.logError ?? (() => {})
    this.#lastFlushAt = this.#now()
  }

  /** Counter-only status. */
  stats(): ModelUsageSinkStats {
    return {
      queued: this.#queue.length,
      flushed: this.#flushed,
      dropped: this.#dropped,
      errors: this.#errors,
      connected: this.#connection !== undefined,
    }
  }

  /** Enqueue one row; never blocks and never throws. */
  enqueue(row: ModelUsageRow): void {
    if (this.#disposed) {
      this.#dropped += 1
      return
    }
    // Overflow path 1 of 2 (dual overflow semantics, design P5-2 in
    // dev-log/2026-08-22-company-market-lockdown-plan-v2.md): a full queue
    // at enqueue drops the OLDEST row; the retry path in #runFlush drops
    // from the opposite end instead.
    if (this.#queue.length >= MODEL_USAGE_QUEUE_LIMIT_ROWS) {
      this.#queue.shift()
      this.#dropped += 1
    }
    this.#queue.push(row)
    if (this.#queue.length >= MODEL_USAGE_FLUSH_THRESHOLD_ROWS) {
      void this.#flush('threshold')
    } else {
      this.#armIntervalTimer()
    }
  }

  /** Best-effort final drain plus connection end; idempotent. */
  async dispose(): Promise<void> {
    if (this.#disposed || this.#disposing) return
    this.#disposing = true
    this.#cancelIntervalTimer()
    this.#cancelRetryTimer()
    if (this.#flushing !== undefined) {
      try {
        await this.#flushing
      } catch {
        // The in-flight flush already logged its own sanitized failure.
      }
    }
    try {
      await this.#runFlush('dispose', true)
    } catch {
      // Best effort by contract; counters were already logged.
    }
    this.#disposed = true
    await this.#endConnection()
  }

  async #flush(trigger: string, force: boolean = false): Promise<void> {
    if (this.#flushing !== undefined) {
      this.#flushAgain = true
      return this.#flushing
    }
    const task = this.#runFlush(trigger, force).then(
      () => {
        this.#flushing = undefined
        if (this.#flushAgain) {
          this.#flushAgain = false
          void this.#flush(trigger)
        } else if (!this.#disposed && this.#queue.length > 0) {
          this.#armIntervalTimer()
        }
      },
      (cause: unknown) => {
        this.#flushing = undefined
        this.#errors += 1
        this.#logError(`dsh-plugin-desktop: model usage flush crashed trigger=${trigger} errors=${String(this.#errors)}: ${sanitizeUsageReportError(cause, this.#dsn)}`)
      },
    )
    // The stored task resolves only after the follow-up bookkeeping above.
    this.#flushing = task.then(() => {}, () => {})
    return task
  }

  async #runFlush(trigger: string, force: boolean): Promise<void> {
    this.#cancelIntervalTimer()
    while (this.#queue.length > 0 && !this.#disposed) {
      if (!force && this.#now() < this.#retryNotBefore) return
      // Dequeue before writing: an overflow drop-oldest while the batch is
      // in flight would otherwise shift the queue under the batch's feet and
      // the completion splice could remove rows that were never sent.
      const rows = this.#queue.splice(0, this.#queue.length)
      try {
        const connection = await this.#connectionRef()
        await connection.query(modelUsageInsertSql(rows.length), rows.flatMap(modelUsageRowValues))
      } catch (cause) {
        // Overflow path 2 of 2 (dual overflow semantics, design P5-2 in
        // dev-log/2026-08-22-company-market-lockdown-plan-v2.md): a failed
        // batch goes back to the front intact, and rows beyond the limit
        // are dropped from the TAIL (newest) — the retry batch must stay
        // complete and the queue bounded through retries, so this end is
        // the opposite of enqueue's drop-oldest.
        this.#queue.unshift(...rows)
        while (this.#queue.length > MODEL_USAGE_QUEUE_LIMIT_ROWS) {
          this.#queue.pop()
          this.#dropped += 1
        }
        this.#errors += 1
        await this.#dropConnection()
        this.#scheduleRetry()
        this.#logError(`dsh-plugin-desktop: model usage flush failed trigger=${trigger} rows=${String(rows.length)} queued=${String(this.#queue.length)} flushed=${String(this.#flushed)} dropped=${String(this.#dropped)} errors=${String(this.#errors)} connection=failed: ${sanitizeUsageReportError(cause, this.#dsn)}`)
        return
      }
      this.#flushed += rows.length
      this.#lastFlushAt = this.#now()
      this.#backoffMs = 0
      this.#logInfo(`dsh-plugin-desktop: model usage flush ok trigger=${trigger} rows=${String(rows.length)} queued=${String(this.#queue.length)} flushed=${String(this.#flushed)} dropped=${String(this.#dropped)} errors=${String(this.#errors)} connection=ok`)
    }
  }

  #armIntervalTimer(): void {
    if (this.#intervalTimer !== undefined || this.#retryTimer !== undefined || this.#disposed || this.#disposing) return
    const delay = Math.max(0, MODEL_USAGE_FLUSH_INTERVAL_MS - (this.#now() - this.#lastFlushAt))
    this.#intervalTimer = this.#schedule(delay, () => {
      this.#intervalTimer = undefined
      void this.#flush('interval')
    })
  }

  #scheduleRetry(): void {
    if (this.#disposed || this.#disposing) return
    this.#backoffMs = this.#backoffMs === 0
      ? MODEL_USAGE_RECONNECT_BASE_MS
      : Math.min(MODEL_USAGE_RECONNECT_MAX_MS, this.#backoffMs * 2)
    this.#retryNotBefore = this.#now() + this.#backoffMs
    this.#cancelRetryTimer()
    this.#retryTimer = this.#schedule(this.#backoffMs, () => {
      this.#retryTimer = undefined
      void this.#flush('retry')
    })
  }

  async #connectionRef(): Promise<ModelUsageConnection> {
    if (this.#connection !== undefined) return this.#connection
    if (this.#connectionTask === undefined) {
      this.#connectionTask = (async () => {
        const boundary = await this.#createBoundary()
        return await boundary.createConnection({
          host: this.#dsn.host,
          port: this.#dsn.port,
          user: this.#dsn.user,
          password: this.#dsn.password,
          database: this.#dsn.database,
          connectTimeout: MODEL_USAGE_CONNECT_TIMEOUT_MS,
        })
      })()
    }
    try {
      this.#connection = await this.#connectionTask
    } catch (cause) {
      this.#connectionTask = undefined
      throw cause
    }
    return this.#connection
  }

  async #dropConnection(): Promise<void> {
    const connection = this.#connection
    this.#connection = undefined
    this.#connectionTask = undefined
    if (connection !== undefined) {
      try {
        await connection.end()
      } catch {
        // A broken connection's end failure is not actionable.
      }
    }
  }

  async #endConnection(): Promise<void> {
    const connection = this.#connection
    this.#connection = undefined
    this.#connectionTask = undefined
    if (connection !== undefined) {
      try {
        await connection.end()
      } catch {
        // Best effort by contract.
      }
    }
  }

  #cancelIntervalTimer(): void {
    this.#intervalTimer?.()
    this.#intervalTimer = undefined
  }

  #cancelRetryTimer(): void {
    this.#retryTimer?.()
    this.#retryTimer = undefined
  }
}

// ---------------------------------------------------------------------------
// Log hygiene
// ---------------------------------------------------------------------------

/**
 * Render one error safe for the log: the DSN's host, host:port, user, and
 * password are replaced before the generic secret masker runs. mysql2
 * failures quote the account and host (`Access denied for user 'u'@'h'`)
 * and connect failures quote `host:port`, so both shapes are stripped.
 * @param error - anything thrown around the write path.
 * @param dsn - the destination whose fragments must not survive.
 * @returns the sanitized message (no stack, no DSN).
 */
export function sanitizeUsageReportError(error: unknown, dsn?: UsageReportDbDsn): string {
  let message = error instanceof Error ? error.message : String(error)
  if (dsn !== undefined) {
    const fragments = [dsn.password, dsn.user, dsn.host, `${dsn.host}:${String(dsn.port)}`]
    for (const fragment of fragments) {
      if (fragment.length === 0) continue
      message = message.replaceAll(fragment, '****')
    }
  }
  return maskSecrets(message)
}

// ---------------------------------------------------------------------------
// Plugin wiring
// ---------------------------------------------------------------------------

/**
 * Read the desktop package version the same way the Electron runtime does
 * (`desktopProductVersion`): the package manifest beside the built module.
 */
export function modelUsageClientVersion(moduleUrl: string = import.meta.url): string {
  const value: unknown = JSON.parse(readFileSync(new URL('../package.json', moduleUrl), 'utf8'))
  if (value === null || typeof value !== 'object'
    || typeof (value as { version?: unknown }).version !== 'string') {
    throw new Error('dsh-plugin-desktop: package.json has no product version')
  }
  return (value as { version: string }).version
}

/** Every dependency `apply` can take from its host; tests substitute all. */
export interface ModelUsageReporterOptions {
  readonly policy?: DesktopPolicy | undefined
  readonly dsnBlob?: string | undefined
  readonly gatewayBlob?: string | undefined
  readonly environment?: NodeJS.ProcessEnv | undefined
  readonly moduleUrl?: string | undefined
  readonly clientVersion?: string | undefined
  readonly createWriteBoundary?: ModelUsageWriteBoundaryFactory | undefined
  readonly schedule?: ModelUsageSchedule | undefined
  readonly now?: (() => number) | undefined
  readonly logInfo?: ((message: string) => void) | undefined
  readonly logError?: ((message: string) => void) | undefined
}

/**
 * Wire the reporter. A `usageReport: false` policy (the dev variant) keeps
 * this plugin completely inert: no subscription, no connection, no blob
 * decode. Resolution failures degrade to an offline reporter with one
 * sanitized log line — telemetry must never fail the boot.
 */
export function apply(ctx: Context, options: ModelUsageReporterOptions = {}): void {
  const logError = options.logError ?? ((message: string) => { ctx.logger.error(message) })
  const logInfo = options.logInfo ?? ((message: string) => { ctx.logger.info(message) })

  let policy: DesktopPolicy
  try {
    policy = options.policy ?? readDesktopPolicy()
  } catch (cause) {
    logError(`dsh-plugin-desktop: model usage reporting stays offline (unreadable policy): ${sanitizeUsageReportError(cause)}`)
    return
  }
  if (policy.usageReport !== true) return

  let dsn: UsageReportDbDsn
  try {
    dsn = resolveUsageReportDbDsn(
      options.dsnBlob,
      options.environment ?? process.env,
      options.moduleUrl ?? import.meta.url,
    )
  } catch (cause) {
    logError(`dsh-plugin-desktop: model usage reporting stays offline (invalid destination): ${sanitizeUsageReportError(cause)}`)
    return
  }

  // Managed-gateway base URL attribution. A corrupt gateway blob already
  // failed this build loudly on the launcher's own decode; here it only
  // degrades the base_url column to ''.
  let gatewayBaseUrl: string | undefined
  try {
    gatewayBaseUrl = managedModelGateway(policy, options.gatewayBlob ?? MODEL_GATEWAY_BLOB)?.baseUrl
  } catch {
    gatewayBaseUrl = undefined
  }

  const sink = new ModelUsageSink(
    options.createWriteBoundary ?? createMysql2WriteBoundary,
    dsn,
    { now: options.now, schedule: options.schedule, logInfo, logError },
  )

  // Registered before the subscription so Cordis's reverse-order disposal
  // stops the firehose first and then drains the queue (async disposer —
  // unloading awaits it inside the launcher's shutdown grace).
  ctx.effect(() => () => sink.dispose(), 'dsh-plugin-desktop: model usage report drain')

  ctx.inject(['sessions'], (sessionsCtx) => {
    sessionsCtx.effect(() => {
      const projection = new ModelUsageProjection({
        clientVersion: options.clientVersion ?? modelUsageClientVersion(options.moduleUrl),
        userEmail: () => ctx.desktopRuntime?.ssoAccountEmail ?? '',
        baseUrlFor: provider =>
          provider === COMPANY_LLM_GATEWAY_PROVIDER_ROUTE ? gatewayBaseUrl ?? '' : '',
      })
      const stopEvents = sessionsCtx.on('session/event', (session, event) => {
        const row = projection.sessionEvent(session, event)
        if (row !== undefined) sink.enqueue(row)
      })
      const stopDisposed = sessionsCtx.on('session/disposed', (session) => {
        projection.sessionDisposed(session)
      })
      return () => {
        stopDisposed()
        stopEvents()
      }
    }, 'dsh-plugin-desktop: model usage collection')
  })
}
