/**
 * Company LLM gateway: obfuscated-blob decoding and the managed-model wiring
 * decision helpers used by the launcher composition and boot.
 *
 * The gateway facts (base URL, api key, model ids) ship as one obfuscated
 * blob generated by `scripts/make-model-gateway-blob.mjs`. Obfuscation is not
 * encryption — see the generator header for the signed-off soft-barrier
 * positioning; the decode below is the runtime peer of that encoder.
 *
 * Everything here is inert unless the embedded policy is `locked` with
 * `managedModels: true`: an open or unlocked build never decodes the blob,
 * never injects the gateway credential, and never registers the provider.
 *
 * @module dsh-plugin-desktop/model-gateway
 */

import { readFileSync } from 'node:fs'
import {
  parseCredentialsDocument,
  resolveSpec,
} from '@deepseek-ai/dsh-credentials-local'
import { type DesktopPolicy } from './desktop-policy.ts'
import { MODEL_GATEWAY_BLOB } from './model-gateway-blob.ts'

/** Loader row id of the pi-ai multi-provider adapter the company route joins. */
export const LLM_PI_AI_ROW_ID = 'llm-pi-ai'
/** Loader row id of the native DeepSeek adapter whose built-in catalog managed builds hide. */
export const LLM_DEEPSEEK_ROW_ID = 'llm-deepseek'
/** Loader row id of the agent default-model selection restated by managed builds. */
export const AGENT_DEFAULT_MODEL_ROW_ID = 'agent-default-model'
/** Loader row id of the web Models settings page hidden by managed builds. */
export const UI_SETTINGS_MODELS_ROW_ID = 'ui-settings-models'

/** The company gateway's registered provider route (also the settings dict key). */
export const COMPANY_LLM_GATEWAY_PROVIDER_ROUTE = 'dsh-company-gateway'
/**
 * Environment variable carrying the gateway api key. The `DSH_` prefix is
 * deliberate: upstream `loadLayeredEnv` rejects `DSH_*` names inside `.env`
 * files, so this value can only come from the inherited environment, the
 * managed credentials document, or this launcher's managed-mode injection —
 * never from a project or home `.env` layer.
 */
export const COMPANY_LLM_GATEWAY_API_KEY_ENV = 'DSH_COMPANY_LLM_KEY'
/** Display name for the provider route on configuration surfaces. */
export const COMPANY_LLM_GATEWAY_DISPLAY_NAME = 'Company LLM Gateway'

/**
 * Fixed XOR key. NOT a secret: it must stay byte-identical to
 * `scripts/make-model-gateway-blob.mjs` or the decode fails loudly.
 */
const OBFUSCATION_KEY = 'dsh-desktop-model-gateway-obfuscation-key-v1'

/** Decoded company model gateway facts; the api key never leaves memory or the environment. */
export interface CompanyModelGateway {
  /** Bare https base URL of the OpenAI-compatible gateway. */
  readonly baseUrl: string
  /** Gateway api key (bearer token). */
  readonly apiKey: string
  /** Served model ids in catalog order; the first entry is the pinned default. */
  readonly models: readonly string[]
}

function invalidBlob(message: string): Error {
  return new Error(`dsh-plugin-desktop: invalid model gateway blob: ${message}`)
}

/**
 * Decode and strictly validate one obfuscated gateway blob.
 * @param blob - base64 XOR-obfuscated JSON payload.
 * @returns the validated gateway facts.
 * @throws when the blob is malformed; the message never includes blob content.
 */
export function decodeModelGatewayBlob(blob: string): CompanyModelGateway {
  if (typeof blob !== 'string' || blob.length === 0) {
    throw invalidBlob('the blob must be a non-empty string')
  }
  let cipher: Buffer
  try {
    cipher = Buffer.from(blob, 'base64')
  } catch (cause) {
    throw invalidBlob(`base64 decoding failed: ${cause instanceof Error ? cause.message : String(cause)}`)
  }
  const key = Buffer.from(OBFUSCATION_KEY, 'utf8')
  const plain = Buffer.from(cipher)
  for (let index = 0; index < plain.length; index += 1) {
    plain[index] = plain[index]! ^ key[index % key.length]!
  }
  let document: unknown
  try {
    document = JSON.parse(plain.toString('utf8')) as unknown
  } catch {
    throw invalidBlob('the decoded payload is not valid JSON')
  }
  if (typeof document !== 'object' || document === null || Array.isArray(document)) {
    throw invalidBlob('the decoded payload must be an object')
  }
  const { baseUrl, apiKey, models } = document as Record<string, unknown>
  const keys = Object.keys(document).sort()
  if (keys.length !== 3 || keys[0] !== 'apiKey' || keys[1] !== 'baseUrl' || keys[2] !== 'models') {
    throw invalidBlob('the decoded payload must carry exactly baseUrl, apiKey, and models')
  }
  if (typeof baseUrl !== 'string' || baseUrl.length === 0) {
    throw invalidBlob('baseUrl must be a non-empty string')
  }
  let url: URL
  try {
    url = new URL(baseUrl)
  } catch {
    throw invalidBlob('baseUrl must be a parseable URL')
  }
  if (url.protocol !== 'https:' || url.username !== '' || url.password !== '') {
    throw invalidBlob('baseUrl must be a bare https URL')
  }
  if (typeof apiKey !== 'string' || apiKey.length === 0) {
    throw invalidBlob('apiKey must be a non-empty string')
  }
  if (!Array.isArray(models) || models.length === 0) {
    throw invalidBlob('models must be a non-empty array')
  }
  const seen = new Set<string>()
  for (const id of models) {
    if (typeof id !== 'string' || id.length === 0) {
      throw invalidBlob('every model id must be a non-empty string')
    }
    if (seen.has(id)) throw invalidBlob(`model "${id}" is listed more than once`)
    seen.add(id)
  }
  return Object.freeze({
    baseUrl,
    apiKey,
    models: Object.freeze([...models]),
  })
}

/**
 * Decode the embedded gateway blob when — and only when — the policy pins the
 * managed-model posture (`locked` && `managedModels`). Every other policy
 * keeps the blob unread and the build fully native.
 * @param policy - embedded desktop policy; omitted or unlocked policies stay inert.
 * @param blob - blob override for tests; defaults to the embedded constant.
 * @returns the gateway facts, or undefined for every unmanaged build.
 * @throws when a managed build carries a corrupt blob (fail closed).
 */
export function managedModelGateway(
  policy: DesktopPolicy | undefined,
  blob: string = MODEL_GATEWAY_BLOB,
): CompanyModelGateway | undefined {
  if (policy?.locked !== true || policy.managedModels !== true) return undefined
  return decodeModelGatewayBlob(blob)
}

/**
 * Environment name the company agent preset's managed-models gate evaluates:
 * a dedicated preset-gate name, deliberately separate from every CLI policy
 * hand-off key (`DESKTOP_POLICY_ENVIRONMENT`). The hand-off carries the RAW
 * `managedModels` flag as one member of an all-five group that
 * `desktopPolicyFromEnvironment` refuses to decode partially, while this
 * gate encodes the EFFECTIVE posture below — one shared name would blur two
 * facts and leave a lone hand-off-shaped key sitting in the shared host
 * environment, poison for any future consumer reading the hand-off from a
 * host snapshot. The `DSH_` prefix keeps this launcher-owned name under the
 * same protections as the other `DSH_*` names: scrubbed out of login-shell
 * captures and rejected by `.env` layers.
 */
export const PRESET_MANAGED_MODELS_GATE = 'DSH_COMPANY_MANAGED_MODELS'

/**
 * The process-environment entry the company agent preset's managed-models
 * gate reads. The Deloitte preset's `tool-web` row carries a `!!js` disabled
 * expression over {@link PRESET_MANAGED_MODELS_GATE} exactly (web search
 * rides api.deepseek.com with `DEEPSEEK_API_KEY`, a credential managed users
 * do not hold), and Loader expressions evaluate in the Host process — so the
 * launcher must write the value into `process.env` before the Host
 * composition loads the preset.
 *
 * The value pins the EFFECTIVE managed posture — `locked` && `managedModels`
 * — and every other build resolves to `'0'`: the launcher writes the entry
 * unconditionally, so an open, unlocked, or development build both evaluates
 * the gate to false and scrubs any stray inherited `'1'`, restoring the
 * native enabled tool exactly as upstream ships it.
 * @param policy - embedded desktop policy of this launch.
 * @returns the environment name and value to write before Host composition.
 */
export function managedModelsPresetGateEntry(
  policy: DesktopPolicy,
): Readonly<{ readonly name: string, readonly value: string }> {
  return {
    name: PRESET_MANAGED_MODELS_GATE,
    value: policy.locked && policy.managedModels ? '1' : '0',
  }
}

/** The `llm-pi-ai` provider profile a managed build registers in memory. */
export interface CompanyModelGatewayProviderProfile {
  /** Selector label. */
  readonly displayName: string
  /** Credential reference resolved per request through the credentials seam. */
  readonly apiKeyEnv: string
  /** OpenAI-compatible wire protocol (the gateway is chat-completions shaped). */
  readonly api: 'openai-completions'
  /** Gateway endpoint. */
  readonly baseURL: string
  /** Served models; capabilities fall back to the route defaults the adapter owns. */
  readonly models: readonly { readonly id: string }[]
}

/**
 * Render the composition-layer `llm-pi-ai` provider profile for the company
 * gateway. The gateway's `/models` endpoint is absent (404), so the model
 * list is exactly the blob's list — no dynamic discovery is attempted. The
 * response is a reasoning-model format regardless of request configuration,
 * so the profile declares no reasoning-effort levels: the harness surfaces
 * the returned reasoning content without asking the gateway to think.
 * @param gateway - decoded company gateway facts.
 * @returns the provider profile pinned into the composition base layer.
 */
export function companyModelGatewayProviderProfile(
  gateway: CompanyModelGateway,
): CompanyModelGatewayProviderProfile {
  return {
    displayName: COMPANY_LLM_GATEWAY_DISPLAY_NAME,
    apiKeyEnv: COMPANY_LLM_GATEWAY_API_KEY_ENV,
    api: 'openai-completions',
    baseURL: gateway.baseUrl,
    models: gateway.models.map(id => ({ id })),
  }
}

/**
 * The default model selection a managed build pins: the gateway's first
 * listed model (the generator writes the pinned default first).
 * @param gateway - decoded company gateway facts.
 * @returns the `agent-default-model` row config values.
 */
export function companyModelGatewayDefaultModel(
  gateway: CompanyModelGateway,
): { readonly provider: string, readonly model: string } {
  const model = gateway.models[0]
  if (model === undefined) throw invalidBlob('the model list is empty')
  return { provider: COMPANY_LLM_GATEWAY_PROVIDER_ROUTE, model }
}

/** Result of the read-only probe over the managed credentials document. */
export type StoredCredentialNames =
  | { readonly status: 'ok'; readonly names: ReadonlySet<string> }
  | { readonly status: 'unreadable'; readonly reason: string }

/**
 * Read-only probe of the credentials document the upstream
 * `dsh-credentials-local` provider owns, parsed with that package's own
 * strict parser so the yield decision uses the store's real semantics
 * instead of an invented reader. Nothing is written; values are never read
 * out — membership in `refs` is the whole question.
 * @param credentialsPath - absolute path of `.credentials.yaml`.
 * @returns the stored reference names, or why the store could not be read.
 */
export function readStoredCredentialNames(credentialsPath: string): StoredCredentialNames {
  let text: string
  try {
    text = readFileSync(credentialsPath, 'utf8')
  } catch (cause) {
    const code = (cause as NodeJS.ErrnoException | null)?.code
    if (code === 'ENOENT') return { status: 'ok', names: new Set() }
    return {
      status: 'unreadable',
      reason: `the credentials document at ${credentialsPath} is unreadable: ${code ?? (cause instanceof Error ? cause.message : String(cause))}`,
    }
  }
  try {
    return { status: 'ok', names: new Set(parseCredentialsDocument(text, credentialsPath).refs.keys()) }
  } catch (cause) {
    return {
      status: 'unreadable',
      reason: cause instanceof Error ? cause.message : String(cause),
    }
  }
}

/** Inputs of the managed-mode environment injection decision. */
export interface ManagedModelGatewayEnvironmentProbe {
  /**
   * Value of {@link COMPANY_LLM_GATEWAY_API_KEY_ENV} in the inherited process
   * environment. An empty string counts as unset, mirroring how the upstream
   * credentials seam treats the environment layer.
   */
  readonly inheritedApiKeyValue: string | undefined
  /** Read-only probe of the managed credentials document. */
  readonly storedCredentials: StoredCredentialNames
}

/** Decision of {@link resolveManagedModelGatewayEnvironment}. */
export type ManagedModelGatewayEnvironmentDecision =
  | { readonly managed: false, readonly reason: 'unmanaged-build' }
  | {
    readonly managed: true
    readonly inject: true
    readonly reason: 'injected'
    readonly environment: Readonly<Record<string, string>>
  }
  | {
    readonly managed: true
    readonly inject: false
    readonly reason: 'user-environment' | 'user-credentials' | 'unreadable-credential-store'
  }

/**
 * Decide whether this launch injects the gateway api key into the process
 * environment, honoring the user-priority yield semantics:
 *
 * - the inherited environment already carries the variable (the layer
 *   `credentials-local` trusts most and treats as read-only), or
 * - the user already stored the reference in `.credentials.yaml`
 *   (the layer the Models page writes),
 *
 * then the user's own configuration wins and this launcher injects nothing.
 * A `.env` file cannot carry the name (upstream rejects `DSH_*` names there),
 * so no third case exists. An unreadable credentials store also yields: the
 * upstream provider will surface that failure on its own load path, and a
 * half-informed injection could not be trusted to lose to a layer it could
 * not read.
 * @param gateway - decoded company gateway facts; undefined for unmanaged builds.
 * @param probe - yield-decision inputs.
 * @returns the injection decision, including the exact environment entry.
 */
export function resolveManagedModelGatewayEnvironment(
  gateway: CompanyModelGateway | undefined,
  probe: ManagedModelGatewayEnvironmentProbe,
): ManagedModelGatewayEnvironmentDecision {
  if (gateway === undefined) return { managed: false, reason: 'unmanaged-build' }
  if ((probe.inheritedApiKeyValue ?? '').length > 0) {
    return { managed: true, inject: false, reason: 'user-environment' }
  }
  if (probe.storedCredentials.status === 'unreadable') {
    return { managed: true, inject: false, reason: 'unreadable-credential-store' }
  }
  if (probe.storedCredentials.names.has(COMPANY_LLM_GATEWAY_API_KEY_ENV)) {
    return { managed: true, inject: false, reason: 'user-credentials' }
  }
  return {
    managed: true,
    inject: true,
    reason: 'injected',
    environment: { [COMPANY_LLM_GATEWAY_API_KEY_ENV]: gateway.apiKey },
  }
}

/**
 * Resolve the credentials document path the same way the upstream provider
 * does, so the probe and the provider can never disagree about the file.
 * @param home - Harness home directory.
 * @returns the absolute `.credentials.yaml` path.
 */
export function storedCredentialsPath(home: string): string {
  return resolveSpec({ dshHome: home }).filename
}
