/** Isolated native window for creating and immediately selecting a Desktop Profile. */

import { BrowserWindow } from 'electron'
import type { DesktopLocale } from './runtime.ts'

const PROFILE_CREATE_SCHEME = 'dsh-profile-create:'
const MAX_NAME_QUERY_BYTES = 1024

interface ProfileCreateCopy {
  readonly title: string
  readonly heading: string
  readonly label: string
  readonly placeholder: string
  readonly start: string
  readonly cancel: string
  readonly empty: string
  readonly failed: string
}

const COPY: Record<DesktopLocale, ProfileCreateCopy> = {
  en: {
    title: 'Add Profile',
    heading: 'Create and start a Profile',
    label: 'Profile name',
    placeholder: 'For example: work',
    start: 'Create and Start',
    cancel: 'Cancel',
    empty: 'Enter a Profile name.',
    failed: 'The Profile could not be created. Check the name and try again.',
  },
  zh: {
    title: '添加配置',
    heading: '创建并启动配置',
    label: '配置名称',
    placeholder: '例如：work',
    start: '创建并启动',
    cancel: '取消',
    empty: '请输入配置名称。',
    failed: '配置创建失败，请检查名称后重试。',
  },
}

export interface ProfileCreateWindowOptions {
  readonly locale: DesktopLocale
  readonly onSubmit: (name: string) => void | Promise<void>
}

export interface ProfileCreateAction {
  readonly action: 'submit' | 'cancel'
  readonly name?: string
}

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')
}

/** Parse only the actions generated by the local profile-create document. */
export function parseProfileCreateAction(href: string): ProfileCreateAction | undefined {
  let url: URL
  try { url = new URL(href) } catch { return undefined }
  if (url.protocol !== PROFILE_CREATE_SCHEME
    || url.username !== '' || url.password !== '' || url.port !== ''
    || url.pathname !== '' || url.hash !== '') return undefined
  const keys = [...url.searchParams.keys()]
  const action = url.hostname
  if (action === 'cancel') return keys.length === 0 ? { action } : undefined
  if (action !== 'submit' || keys.length !== 1 || keys[0] !== 'name') return undefined
  const name = url.searchParams.get('name')
  if (name === null || Buffer.byteLength(name, 'utf8') > MAX_NAME_QUERY_BYTES) return undefined
  return { action, name }
}

function documentHtml(locale: DesktopLocale): string {
  const copy = COPY[locale]
  const values = Object.fromEntries(Object.entries(copy).map(([key, value]) => [key, escapeHtml(value)])) as Record<keyof ProfileCreateCopy, string>
  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; form-action 'none'; base-uri 'none'"><style>
    :root { color-scheme: light dark; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    body { margin: 0; padding: 24px; color: CanvasText; background: Canvas; }
    h1 { margin: 0 0 18px; font-size: 18px; font-weight: 600; }
    label { display: block; margin-bottom: 7px; font-size: 13px; }
    input { box-sizing: border-box; width: 100%; padding: 9px 10px; border: 1px solid ButtonBorder; border-radius: 6px; background: Field; color: FieldText; font: inherit; }
    #error { min-height: 18px; margin: 7px 0 0; color: #c62828; font-size: 12px; }
    footer { display: flex; justify-content: flex-end; gap: 8px; margin-top: 10px; }
    button { min-width: 88px; padding: 8px 12px; border: 1px solid ButtonBorder; border-radius: 6px; background: ButtonFace; color: ButtonText; font: inherit; cursor: pointer; }
    button.primary { background: #4f46e5; border-color: #4f46e5; color: white; }
  </style></head><body><main>
    <h1>${values.heading}</h1>
    <label for="name">${values.label}</label>
    <input id="name" type="text" maxlength="255" placeholder="${values.placeholder}" autofocus>
    <p id="error" role="alert"></p>
    <footer><button id="cancel" type="button">${values.cancel}</button><button id="start" class="primary" type="button">${values.start}</button></footer>
  </main><script>
    const input = document.getElementById('name');
    const error = document.getElementById('error');
    const submit = () => {
      const name = input.value.trim();
      if (!name) { error.textContent = ${JSON.stringify(copy.empty)}; input.focus(); return; }
      location.href = ${JSON.stringify(`${PROFILE_CREATE_SCHEME}//submit?name=`)} + encodeURIComponent(name);
    };
    document.getElementById('start').addEventListener('click', submit);
    document.getElementById('cancel').addEventListener('click', () => { location.href = ${JSON.stringify(`${PROFILE_CREATE_SCHEME}//cancel`)}; });
    input.addEventListener('keydown', (event) => { if (event.key === 'Enter') submit(); });
  </script></body></html>`
}

/** Own one isolated profile-create window; repeated opens focus the same instance. */
export class ProfileCreateWindow {
  private window: BrowserWindow | undefined
  private busy = false
  private disposed = false

  constructor(private readonly options: ProfileCreateWindowOptions) {}

  open(): void {
    const existing = this.window
    if (existing !== undefined && !existing.isDestroyed()) {
      existing.show()
      existing.focus()
      return
    }
    this.disposed = false
    this.busy = false
    const copy = COPY[this.options.locale]
    const window = new BrowserWindow({
      title: copy.title,
      width: 420,
      height: 250,
      minWidth: 360,
      minHeight: 220,
      resizable: false,
      show: false,
      autoHideMenuBar: true,
      backgroundColor: '#202124',
      webPreferences: {
        contextIsolation: true,
        nodeIntegration: false,
        nodeIntegrationInSubFrames: false,
        sandbox: true,
        webSecurity: true,
        webviewTag: false,
        spellcheck: false,
      },
    })
    this.window = window
    window.accessibleTitle = copy.title
    window.removeMenu()
    window.webContents.setWindowOpenHandler(() => ({ action: 'deny' }))
    const navigate = (event: Electron.Event, href: string): void => {
      const action = parseProfileCreateAction(href)
      event.preventDefault()
      if (action !== undefined) void this.handleAction(action)
    }
    window.webContents.on('will-navigate', navigate)
    window.webContents.on('will-redirect', navigate)
    window.once('ready-to-show', () => {
      if (!this.disposed && this.window === window && !window.isDestroyed()) window.show()
    })
    window.on('closed', () => {
      window.webContents.off('will-navigate', navigate)
      window.webContents.off('will-redirect', navigate)
      if (this.window === window) this.window = undefined
    })
    void window.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(documentHtml(this.options.locale))}`).catch(() => {
      if (!this.disposed && this.window === window) window.close()
    })
  }

  close(): void {
    this.disposed = true
    const window = this.window
    this.window = undefined
    if (window !== undefined && !window.isDestroyed()) window.close()
  }

  private async handleAction(action: ProfileCreateAction): Promise<void> {
    if (this.busy || this.disposed) return
    if (action.action === 'cancel') {
      this.close()
      return
    }
    const name = action.name?.trim()
    if (name === undefined || name.length === 0) return
    this.busy = true
    try {
      await this.options.onSubmit(name)
      this.close()
    } catch {
      this.busy = false
      const window = this.window
      if (window === undefined || window.isDestroyed()) return
      const message = JSON.stringify(COPY[this.options.locale].failed)
      await window.webContents.executeJavaScript(
        `document.getElementById('error').textContent = ${message}; document.getElementById('name').focus()`,
        true,
      ).catch(() => {})
    }
  }
}
